= Getting Started 

== Prerequisites

To use the AeroGear SDK for iOS, you will need the following installed on your development machine:

* iOS 9 or later
* Xcode 9 or later
* link:https://cocoapods.org/[CocoaPods]

To get started with the AeroGear iOS SDK, you can set up the SDK in your existing or new project. The SDK is written in Swift. 

=== CocoaPods

1) The AeroGear SDK for iOS is available using the CocoaPods package manager.
If you have not installed CocoaPods, install it by running the command:

[source,bash]
----
$ gem install cocoapods
$ pod setup
----

2) In your project directory (the directory where your `.xcodeproj` file is), create a plain text file named `Podfile` (without any file extension) and add the lines below. Replace `YourTarget` with your actual target name.

.Podfile
[source,ruby]
----
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target :'YourTarget' do
    ## Require one of the AeroGear SDK's here
    pod 'AGSPush'
    pod 'AGSAuth'
end
---- 

3) Then run the following command:
    
[source,bash]
----
$ pod install
----

4) Open up `.xcworkspace` with Xcode and start using the SDK.

> Do not use `.xcodeproj`. If you open up a project file instead of a workspace, dependencies will not be correctly configured.

== Getting Started with Swift

1) Import SDK you want to use in the application.
For example:

[source,swift]
----
   import AGSAuth
----

2) Use imported SDK library

Please follow each individual SDK documentation for more information 
about usage.
