include::{partialsdir}/attributes.adoc[]

= Getting Started with AeroGear Mobile Services
:toc:
include::installing-mobile-services.adoc[leveloffset=1]
[[registering]]
include::{partialsdir}/registering-a-mobile-app.adoc[leveloffset=1]
[[provisioning]]
== Provisioning your First Service

Mobile Services provide commonly required features for mobile app development.

This guide introduces the procedures for using mobile services by guiding you through the process using the Identity Management service. For a full list of available services see xref:con_services.adoc[Mobile Services]

:service-name: Identity Management

include::{partialsdir}/generic-provisioning.adoc[]

When provisioning a {keycloak-service} service, you are prompted to set the following configuration:

* *Keycloak admin username*: Username for Keycloak administration

* *Keycloak admin password*: Password for the Keycloak admin user

* *Name of the Keycloak realm*: Name of the keycloak realm. (defaults to current namespace)

NOTE: A realm manages a set of users, credentials, roles, and groups. A user belongs to and logs into a realm. Realms are isolated from one another and can only manage and authenticate the users that they control.

* *Connect to an existing shared service*: Select if you want to use an existing service and you have the URL and credentials to use that service.

* *URL of the shared service*: Enter a value if you want to use an existing shared service.

include::{partialsdir}/generic-provisioning-end.adoc[]


[[binding]]
include::keycloak/binding.adoc[leveloffset=1]
[[localdev]]
== Setting Up your Local Development Environment

=== Supported Environments

In order to perform local development, you will need to have set up a local development environment or IDE. {product-name} supports mobile app development across iOS Native, Android Native, Cordova and Xamarin. For information on how to set up your local development environment for these technologies, please see the links below:

* link:https://developer.android.com/studio/install[Android]
* link:https://developer.apple.com/library/archive/referencelibrary/GettingStarted/DevelopiOSAppsSwift/index.html[iOS]
* link:https://cordova.apache.org/#getstarted[Cordova]
* link:https://developer.xamarin.com/getting-started/[Xamarin]

include::keycloak/configuring-dev-env-keycloak.adoc[leveloffset=2]
[[running]]

== Running your First Mobile App

=== Clone the showcase app:

include::{partialsdir}/cloning-showcase-app.adoc[]

include::{partialsdir}/proc_self-signed-certs.adoc[leveloffset=2]

include::{partialsdir}/generic-obtaining-the-mobile-sdk-config-file.adoc[leveloffset=2]

=== Running the Mobile App in an Emulator

include::{partialsdir}/running-app-in-emulator.adoc[leveloffset=1]