include::{partialsdir}/attributes.adoc[]

= Getting Started with AeroGear Mobile Services
:toc:
include::installing-mobile-services.adoc[leveloffset=1]
[[registering]]
include::{partialsdir}/registering-a-mobile-app.adoc[leveloffset=1]
[[provisioning]]
== Provisioning your First Service

Mobile Services provide commonly required features for mobile app development.

The following services are available with this release:


* xref:identity-management.adoc[{keycloak-service}]
* xref:push-notifications.adoc[{unifiedpush-service}]
* xref:runtime-connector.adoc[{custom-service}]
* xref:mobile-metrics.adoc[{metrics-service}]
* xref:mobile-cicd.adoc[{digger-service}]
* xref:device-security.adoc[{device-security-service}]


This guide introduces the procedures for using mobile services by guiding you through the process for running an Android app using the Identity Management service. 

include::keycloak/provisioning.adoc[leveloffset=1]
[[binding]]
include::keycloak/binding.adoc[leveloffset=1]
[[localdev]]
== Setting Up your Local Development Environment

=== Supported Environments

In order to perform local development, you will need to have set up a local development environment or IDE. {product-name} supports mobile app development across iOS Native, Android Native, Cordova and Xamarin. For information on how to set up your local development environment for these technologies, please see the links below:

* link:https://developer.android.com/studio/install[Android]
* link:https://developer.apple.com/library/archive/referencelibrary/GettingStarted/DevelopiOSAppsSwift/index.html[iOS]
* link:https://cordova.apache.org/#getstarted[Cordova]
* link:https://developer.xamarin.com/getting-started/[Xamarin]

include::keycloak/configuring-dev-env-keycloak.adoc[leveloffset=2]
[[running]]

== Running your First Mobile App

A few showcase apps have been created to allow you to try out some of the features. They are available in several different platforms. Please pick one platform that you are interested in and follow the steps below to set it up.

=== Clone the showcase app

Please choose one platform and clone the corresponding showcase app.

include::{partialsdir}/cloning-showcase-app.adoc[]

=== Configure the showcase app

You need to configure the showcase app by updating the `mobile-services.json` file.

include::{partialsdir}/configure-showcase-apps.adoc[]

Before building and running the showcase app, we also need to configure the device to make sure it will accept self-signed certificates.

include::{partialsdir}/proc_self-signed-certs.adoc[leveloffset=2]

We can now build and run the showcase app.

include::{partialsdir}/build-and-deploy.adoc[leveloffset=1]


