include::{partialsdir}/attributes.adoc[]

= Setting up {org-name} {product-name} on OpenShift

To use {product-name}, you must run OpenShift and install an add-on which enables {product-name}. For more information about OpenShift, see https://www.openshift.org/.

NOTE: {org-name} recommends running OpenShift using the method described here. However there are many ways to run OpenShift, and {product-name} is compatible with most of these methods. There is a known issue with Minishift that makes it unsuitable for mobile development. This issue is described in link:https://github.com/minishift/minishift/issues/1287[].

== Prerequisites

* MacOS or Linux

* link:https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html[Ansible] (tested with version 2.4, but should work with version 2.3 or later)

* link:https://www.openshift.org/download.html[OpenShift client tools] version 3.9 or later
+
WARNING: OpenShift oc executable must be located in a system location that is known to all shells (e.g. /usr/local/bin)

* Docker must be version 17.09.1 in order to be compatible with the latest release of OpenShift and depending on your OS this is downloaded from different places:

[role="primary"]
.MacOS

****
You can download Docker CE for MacOS version 17.09.1 link:https://download.docker.com/mac/stable/19543/Docker.dmg[here].
****

[role="secondary"]
.Linux

****
You can download Docker CE version 17.09.1 for rpm based distros from link:https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-17.09.1.ce-1.el7.centos.x86_64.rpm[here]. Otherwise have a look link:https://docs.docker.com/install[here].
****

== Local development

. Clone the Mobile-core installer:
+
We configure the local development installation of {org-name} {product-name} using ansible scripts in our link:https://github.com/aerogear/mobile-core[mobile-core] repo. Clone this repo to your local machine and check out the {release-number} tag using:
+
[source,bash,subs="attributes"]
----
git clone git@github.com:aerogear/mobile-core.git
cd mobile-core
git checkout {release-number}
----

. Perform the installation:
+
In the cloned repository, run the installer with the following command:
+
[source,bash]
----
./installer/install.sh
----
+
This validates that Ansible, Docker and the OpenShift Client Tools
are installed and are the right version.
+
Once verified it prompts you for your Docker Hub login credentials, which
must be valid for the installation to continue.
+
The next set of values are optional and can be left with the default values:
+
[source,bash,subs="attributes"]
----
DockerHub Tag (Defaults to {release-number}):
DockerHub Organisation (Defaults to aerogearcatalog):
Cluster IP (Defaults to 192.168.37.1):
Wildcard DNS Host (Defaults to nip.io):
----
+
The first two values here are used to configure the service-catalog in the
resulting cluster to look at other docker registries or tags to fetch the
APBs from, but unless you are already familiar with editing these values,
the defaults are the safest option.
+
The following 2 options alter what IP address and wildcard DNS host you wish
to use.

. Check the Cluster IP:
+
In order to allow communication between your mobile device and the cluster, the
cluster IP must be in the same c-block as your local network.
+
i.e. If your local router which both your workstation and mobile are connected to
a router using the `10.0.0.x` c-block, then you should set the cluster IP to an IP
in the `10.0.0.x` c-block too, such as `10.0.0.135`.

. Check the installation logs:
+
The following installation can take a while the first time it runs as it pulls a number of docker images. Once completed successfully, this will end with output similar to:
+
----
TASK [output-oc-cluster-status : debug] ******************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "Web console URL: https://192.168.37.1:8443/console/",
        "",
        "Config is at host directory /var/lib/origin/openshift.local.config",
        "Volumes are at host directory /var/lib/origin/openshift.local.volumes",
        "Persistent volumes are at host directory /var/lib/origin/openshift.local.pv",
        "Data is at host directory /path/to/mobile-core/ui/openshift-data"
    ]
}

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=44   changed=17   unreachable=0    failed=0
----
+
Which signifies that your installation has completed successfully.

. Verify the installation:
+
.. Open a browser and (accepting the self-signed certificate) navigate to:
+
----
https://192.168.37.1:8443/console/
----
+
The developer login credentials are:
+
----
username: developer
password: password
----

.. Once logged in look for the "Mobile" category across the top of the catalog package which indicates that the mobile features of {org-name} {product-name} have been succesfully installed.

== Next Steps

* xref:con_services.adoc[Provision] a Mobile Service

* xref:apps.adoc[Register] a Mobile App

== Troubleshooting

=== Switching from a different Docker version on Fedora 28

. link:https://docs.docker.com/install/linux/docker-ce/fedora/#uninstall-old-versions[Uninstall] the old Docker version

. link:https://docs.docker.com/install/linux/docker-ce/fedora/#install-from-a-package[Install] Docker 17.09.1 from the rpm package

. Make sure that Docker can be managed by non-root users by following link:https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user[this guide]
