include::{partialsdir}/attributes.adoc[]
= {mobile-client}s in OpenShift

== Introduction

{mobile-client}s in OpenShift allow you to perform Cloud Native Mobile App Development using OpenShift as the back end
for your mobile apps. A {mobile-client} is a representation of the mobile app that you are developing locally.
{mobile-client}s allow you bind your mobile app to mobile services such as {keycloak-service}, {unifiedpush-service},
{metrics-service} and others. This makes many of the common tasks associated with mobile development much easier and
quicker to implement.

A configuration file named `mobile-services.json` acts as the link between your {mobile-client} in OpenShift
and your local app in development. This configuration file is used to initialize the {SDK} in your mobile app
and to connect to the back end {product-name} you have provisioned on OpenShift.

[#registering]
include::{partialsdir}/mobile-client-registering-a-mobile-client.adoc[leveloffset=1]

[#services]
include::{partialsdir}/mobile-client-viewing-available-services.adoc[leveloffset=1]

[#binding]
include::{partialsdir}/mobile-core-binding-mobile-services.adoc[leveloffset=1]

[#building]
include::{partialsdir}/mobile-client-configuring-and-running-builds.adoc[leveloffset=1]

