include::{partialsdir}/attributes.adoc[]

== Provisioning {product-name}


== Prerequisites

* [x] You are running OpenShift with {product-name} as described in xref:ROOT:installing-mobile-services.adoc[Setting up AeroGear {product-name} on OpenShift].

TIP: If you have registered a mobile app, you can navigate to that {mobile-client} and see what mobile services are available to provision.  

include::{partialsdir}/generic-provisioning.adoc[]


After the service has been provisioned, you should then be able to see the service's secret and config map created during provision
within the project's resources.

To edit the service configuration, go to *Resources* -> *Config Maps* and select the service's config map.
Press the *[Actions]* button in the upper right corner and choose *[Edit]* or *[Edit YAML]*. This
allows you to edit the service's configuration directly which is then exposed to your mobile application.

== Deprovisioning
In order to delete a provisioned service, select the service menu and click *Delete*. A notification 
appears that the service has now been *Marked for Deletion*.