include::{partialsdir}/attributes.adoc[]

= Registering a Mobile App

Prerequisites:

* [x] You have installed Minishift with the mobilecore addon as described in xref:minishift_install.inc.adoc[Getting Started].

You register a mobile app by creating a mobile app record in OpenShift:

. Log into the OpenShift console.
. Click *Add to Project* and choose *Browse Catalog* from the options.
+
You can filter the catalog items to only show mobile specific items by clicking the *Other* tab.
. Choose the mobile platform (Android, iOS, Cordova or Xamarin) and follow the wizard.

After the {mobile-client} is provisioned, you can navigate to it from Project Overview. This screen dislays a list of mobile services that you can associate with the {mobile-client} and offers to provision any mobile service that is in the service catalog but is not currently provisioned. 

== Related Information

* xref:provisioning-services.adoc[provisioning a mobile service]
* xref:binding-mobile-app-record-to-mobile-services.adoc[binding a mobile app record with a mobile service]
