include::{partialsdir}/attributes.adoc[]

= Using {custom-service} in an App


== Retrieving the Custom Configuration in a {mobile-client}

This section shows how to retrieve the configuration of the custom service in a {mobile-client} by using the Core module of the Aerogear SDK.

[role="primary"]
.Android
****
. If you do not use any other modules of the Aerogear SDK, make sure that the `android-core` is in the dependencies of your `app` module's `build.gradle`:
+
[source,groovy,subs="attributes"]
----
dependencies {
    implementation 'org.aerogear:android-core:{release-number}'
}
----

. Use the `getServiceConfigurationById` method to get the service configuration associated with your custom service:
+
[source,java]
----
ServiceConfiguration customConfig = MobileCore.getInstance().getServiceConfigurationById("[SERVICE NAME]");
----

. Get the URL of the custom service:
+
[source,java]
----
String url = customConfig.getUrl();
----

. Get custom configuration properties (specified in *Service JSON Configuration* at provision time):
+
[source,java]
----
String property = customConfig.getProperty("[PROPERTY NAME]");
----

****

[role="secondary"]
.iOS
****
. If you do not use any other modules of the Aerogear SDK, make sure that the `AGSCore` is in your `Podfile`:
+
[source,ruby,subs="attributes"]
----
target :'YourTarget' do
    pod 'AGSCore', '{release-number}'
end
----

. Use the `getConfigurationById` function to get the service configuration associated with your custom service:
+
[source,swift]
----
let customConfig = AgsCore.instance.getConfigurationById("[SERVICE NAME]")
----

. Get the URL of the custom service:
+
[source,swift]
----
let url = customConfig.url
----

. Get custom configuration properties (specified in *Service JSON Configuration* at provision time):
+
[source,swift]
----
let property: JSONValue = customConfig.config["[PROPERTY NAME]"]
----

****

[role="secondary"]
.Cordova
****
. Use the `getConfigById` function to get the service configuration associated with your custom service:
+
[source,javascript,subs="attributes"]
----
const core = require("@aerogear/core").INSTANCE;
const customConfig = core.getConfigById("[SERVICE NAME]");
----
+
NOTE: `@aerogear/core` is a dependency of `@aerogear/app` which should always be installed because it contains the `init`function to initialize all other SDK modules.

. Get the URL of the custom service:
+
[source,javascript]
----
const url = customConfig.url;
----

. Get custom configuration properties (specified in *Service JSON Configuration* at provision time):
+
[source,javascript]
----
// customConfig.config contains the parsed Service JSON Configuration
const property = customConfig.config["[PROPERTY NAME]"];
----

****

[role="secondary"]
.Xamarin
****
. Use the `GetServiceConfigurationById` function to get the service configuration associated with your custom service:
+
[source,csharp]
----
var customConfig = MobileCore.Instance.GetServiceConfigurationById("[SERVICE NAME]");
----

. Get the URL of the custom service:
+
[source,csharp]
----
var url = customConfig.Url;
----

. Get custom configuration properties (specified in *Service JSON Configuration* at provision time):
+
[source,csharp]
----
var property = customConfig["[PROPERTY NAME]"];
----
****
