
//':context:' is a vital parameter. See: http://asciidoctor.org/docs/user-manual/#include-multiple
:context: proc_building-a-mobile-app

[id='{context}_proc_building-a-mobile-app']
= Building a Mobile App

To build a mobile app.

. Log in to the OpenShift Console.

. Browse to the *Project Overview* screen and find the {mobile-client} you want to build.

. Click on the name of the {mobile-client} to open the details view.

. From the *Builds* tab, select the mobile app you want to build click *Start Build*.
+
NOTE: Expanding the build section will show the current status of this build.

. Check the mobile app build status by expanding the mobile client box.
+
NOTE: This box lists the last 5 builds for this client.

. To view the mobile app as a pipeline build, from the left menu, click *Builds > Pipeline*.
+
Each build step is displayed (along with the current step status: completed, error or running) based on the stages in your Jenkinsfile code.

.  To view the full build log, click *view log* which redirects you to your Jenkins instance.
