include::{partialsdir}/attributes.adoc[]

= Monitoring {keycloak-service} Service

== Prerequisites

* [x] You have provisioned the {metrics-service} Service as described in xref:metrics/provisioning.adoc[Provisioning {metrics-service} Service].
* [x] You have provisioned the {keycloak-service} Service as described in xref:keycloak/provisioning.adoc[Provisioning {keycloak-service} Service].


NOTE: The {metrics-service} Service and {keycloak-service} Service must be provisioned in the same OpenShift project to access data.

== Overview

After the {metrics-service} Service (includes Grafana tool and Prometheus monitoring system) and {keycloak-service} Service are provisioned,
you should be able to see the "Keycloak Metrics" in the list of available dashboards 
(navigate to Grafana's exposed URL -> Log in -> Home -> Select *Keycloak Metrics*).

== Dashboard's panels description

Keycloak dashboard consists of several panels which give you overview of the specific
events, such as number of registered users, memory usage etc.

See below for the detailed description of each panel and its values

=== Singlestat Panels

==== Total Registrations

Total number of registered (non-admin) users. This number comprises all successful registrations made via various providers, e.g. Keycloak, Github, Facebook etc.

==== Total Logins

Total number of successful logins (only non-admin users) over all providers.

==== Total Login Errors

Total number of failed login attempts.

==== Current Memory

The amount of memory currently used by the {keycloak-service} Service

=== Graph panels

==== Logins

Overview of the successful logins over time

==== Login Errors

Overview of the failed login attempts over time

==== Memory Usage

The values in this graph represents the following:

. *Used* - The amount of memory currently used by the {keycloak-service} Service
. *Commited* - The amount of memory that is guaranteed to be available for use (by JVM)
. *Max* - The maximum amount of memory that can be used for memory management


=== Pie Charts

==== Logins Per Provider

Overview of the successful (non-admin) user logins per provider

==== Registrations Per Provider

Overview of the successful (non-admin) user registrations per provider.


== External resources

* link:http://docs.grafana.org/features/panels/singlestat/#singlestat-panel[Singlestat Panel]
* link:http://docs.grafana.org/features/panels/graph/#graph-panel[Graph Panel]
* link:https://grafana.com/plugins/grafana-piechart-panel[Pie Chart]
