

= Handling Push Notifications

Follow the next steps to handle incoming {push-notification}s in your foregrounded application.

NOTE: {push-notification}s that arrive when the application is in the background will always be handled by the OS.

[tabs]
====
// tag::excludeDownstream[]
Android::
+
--
Add to your project an implementation of *MessageHandler*:

[source,java]
----
public class MyMessageHandler implements MessageHandler {

    @Override
    public void onMessage(Context context, Map<String, String> message) {
        // Handle incoming message
    }

}
----

Add it to your application's manifest.

[source,xml]
----
<meta-data
    android:name="DEFAULT_MESSAGE_HANDLER_KEY"
    android:value=".MyMessageHandler" />
----

--
iOS::
+
--

The {SDK} for iOS does not provide a way to handle incoming messages. Instead, follow the link:https://developer.apple.com/notifications/[Apple's official documentation^] about notifications.

--
// end::excludeDownstream[]
Cordova::
+
--

The {SDK} for JavaScript does not provide a way to handle incoming messages. We recommend using the link:https://ionicframework.com/docs/native/push[Ionic Push plugin^].

--
// tag::excludeDownstream[]
Xamarin::
+
--
This feature is not yet supported in the AeroGear Xamarin SDK
--
// end::excludeDownstream[]
====
