= Documentation for AeroGear Mobile Services 

This README contains the guidelines and standards for contributing to AeroGear documentation. The documentation is written in link:https://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc, window="_blank"] and published by link:docs.antora.org[Antora, window="_blank"].

- If you see an issue in documentation, link:https://github.com/aerogear/mobile-docs/issues/new[raise an issue^] and post a PR with a fix for a review. Please include as much information as possible.
- See the link:https://github.com/aerogear/mobile-docs/projects/1[Kanban board^].

:toc: 1

== Writing AeroGear Documentation
- (WIP) Write documentation that adheres to xref:#mod-docs[Modular Documentation Principles].
- Name files by slugifying titles
`Registering a Mobile App` -> `registering-a-mobile-app.adoc`
- Determine which functionality is the change related to?
+
* A specific mobile service
* Common to all mobile services
* Common to all services or SDKs but with some information that is specific to each.
+
With this information, you should be able to determine where the file should be located in the repo, for example `modules/ROOT/push`
+
If you intend to reuse a part of a file, create a partial in modules/ROOT/_partials and refer to it using an `include` directive.

- If you make a filename change (for example adding or renaming a file), you must update the appropriate `modules/ROOT/nav.adoc` file. 

- Stick to present tense, for example `When you add the dashboard, it appears on ...`, not `When you add the dashboard, it will appear on ...`

- Test your changes xref:#using-antora[using Antora].


When editing a file, you might find that the content is not in the associated adoc file, because it's rendered by using the asciidoc `include` command. You can edit the included file, but note that editing the source file can have unintended effect. 

For example, when editing the `registering-an-app.adoc`, avoid problems by: 

. Regex search for `include.*registering-an-app` across the whole repo.
. Review the list of files from this search to understand of the context of the content.
. Use your judgement when editing the file to make sure the content is appropriate for each rendering of that content. 
 
[mod-docs]
=== Modular Documentation Principles

See link:https://redhat-documentation.github.io/modular-docs/[Modular Docs and Templates, window="_blank"].

.Concept
An introduction to a new term, process, module or component. For example, "Mobile Service" : what is it? why do I care? and how does it fit into my development environment?

* Prefix file names with con_

.Procedure
See link:https://redhat-documentation.github.io/modular-docs/#creating-procedure-modules[Creating Procedures]

* Prefix filenames with proc_
+
. Who should perform this procedure?
. Why am I performing this procedure? benefits or context in a higher level user story
. What is the object of the task? For example adding a dashboard.. to what?
. What do I need to know and/or do before installing or provisioning the software?
. What do I need to do to provision the software?
. What are the minimum configuration tasks that I need to do to get value from the software?
. What additional information would be useful to give after completing the procedure ? (For example "Next steps")



.Reference
* Prefix filenames with ref_

Information user might need to debug or extend the normal usage of AeroGear software. For example:

* API syntax and definitions
* Configuration options

=== AsciiDoc text document format

"AsciiDoc is a text document format for writing notes, documentation, articles, books, ebooks, slideshows, web pages, man pages and blogs."

See link:http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc syntax quick reference^]:

* Avoid using headings with `--, ~~, ^^, ++`
* Avoid using Markdown
* Try to use syntax highlighting wherever possible, for example `[source, bash]`

[[using-antora]]
== Using Antora to convert AsciiDoc to HTML

NOTE: You can avoid using Antora to preview the docs with online tool as described in https://github.com/finp/mobile-netlify

After modifying the documentation, validate your changes and preview the results with Antora:

. Install Antora globally as described in their https://docs.antora.org/antora/1.0/install/install-antora/[install guide].
+
NOTE: As part of Antora installation, install site-generator globally.
+
If you encounter a libcurl error on Linux, follow the `Option 1: Create missing symlink` in instructions at: https://docs.antora.org/antora/1.0/install/troubleshoot-nodegit/


. Fork this repo and set up origin and upstream remotes.

. Change to the `mobile-docs` directory.

. Run Antora:
+
----
./bin/quick-build.sh
----
+
Note: <site-file> refers to either:
+
* local-site - your current directory
* site.yml - the master branch of the github repo
+ 
When building for publication use:
+
----
./bin/build.sh
----
+


NOTE: After changes to link:https://github.com/aerogear/antora-ui[antora-ui], you might need to run 'antora --pull --clean <site-file>' to pick up those changes.




=== Previewing and Posting a PR for Publishing

. Run Antora:
+
----
./bin/build.sh
----

. Review the rendered HTML(`build\site\index.html`):
+
NOTE: Check for correct styling changes as well.
+
. Make a PR against  https://github.com/aerogear/docs.aerogear.org

NOTE: This repo contains more than just the output of mobile-docs repo. See https://github.com/aerogear/docs.aerogear.org/blob/master/README.adoc for more details.

=== References to Remote Repos (to code, external documentation)

No remote repos were harmed in the production of this documentation ;)

References to code can be included as follows:

1. Decide on a name for the snippet, for example push-ios-register 

2. Create a partial in mobile-docs, for example:
https://github.com/aerogear/mobile-docs/blob/master/modules/ROOT/pages/_partials/push-ios-register.inc

3. Reference the code file you want to use (with a tags filter):
+
----
 include::https://raw.githubusercontent.com/aerogear/ios-showcase-template/push-push/ios-showcase-template/push/PushHelper.swift[tags=push-ios-register]
----

4. Add tags to the code repo, for example: 
+
----
// tag::push-ios-register[]
    public func registerUPS(_ deviceToken: Data) {
        AgsCore.logger.info("Registered for notifications with token")

        var config = UnifiedPushConfig()
        config.alias = "Example App"
        config.categories = ["iOS", "Example"]

        AgsPush.instance.register(
            deviceToken,
            config,
            success: {
                AgsCore.logger.info("Successfully registered to Unified Push Server")
            },
            failure: { (error: Error!) in
                AgsCore.logger.error("Failure to register for on Unified Push Server: \(error)")
            }
        )
    }
// end::push-ios-register[]

----

5. Edit adoc file with the following to display the content:
+
----
 include::{partialsdir}/push-ios-register.inc-rantora.adoc[]
----
+
NOTE: You need to run mobile-docs:/bin/build.sh <site>.yml to make sure the temp files are in place when building site