= Mobile Docs

Our goal is to help users of AeroGear projects "understand things well and not feel like they're dealing with a capricious minor god instead of a product." footnote:[Laura Bailey]

This readme introduces the standards for AeroGear docs.

:toc: 1

== Concepts, Procedures and Reference

Concept::
An introduction to a new term, process, module or component. For example, "Mobile Service" : what is it? why do I care? and how does it fit into my development environment?

Procedure::
The important information that gets me using AeroGear software, for example, write your procedure by answering the following questions:
+
. Who should perform this procedure?
. Why am I performing this procedure? benefits or context in a higher level user story
. What is the object of the task? eg adding a dashboard.. to what?
. What do I need to know and/or do before installing or provisioning the software?
. What do I need to do to provision the software?
. What are the minimum configuration tasks that I need to do to get value from the software?
. What additional information would be useful after completing procedure (eg, next steps)

Reference::
Information I might need to debug or extend the normal usage of AeroGear software. For example:
+
* API syntax and definitions
* Configuration optionss 


== Writing AeroGear Documentation

. If the documentation relates to a single sdk or service, make a PR against that repo. Note all adoc files that get published are located in the /docs directory and must conform to Antora standards.
. If you make a filename change (eg adding or renaming a file), you must update the appropriate nav.adoc file. 
. Test your changes xref:#using-antora[using Antora]
. Determine which functionality is this documentation related to?
+
* Push
* Sync
* Common to all mobile services
* Common to all services or SDKs but with some information that is specific to each.
+
With this information, you should be able to make a PR against the appropriate repo. For, example, a doc relating to all services is best placed in this repo.
+
If you have a mix of common and specific information, raise an issue on this repo to address.


. Stick to present tense, eg `When you add the dashboard, it appears on ...`, not `When you add the dashboard, it will appear on ...`


== Asciidoc

For a fuller list of asciidoc syntax, see link:http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[the quick reference], note the following syntax to avoid:

* Headings using --, ~~, ^^, ++ syntax
* Markdown
* Source block without syntax. Try to use syntax highlighting where possible, for example `[source, bash]`

[NOTE]
--
This page acts as example of documentation best practises:

* introducing terms
* a single  procedure
* reference material
--

== Modular Docs

For more information and some useful templates, see link:https://redhat-documentation.github.io/modular-docs/[Modular Docs]

[[using-antora]]
== Using Antora to convert asciidoc to html

After modifying documentation, you can validate your changes and preview the results by:

. Install Antora globally as described in their https://docs.antora.org/antora/1.0/install/install-antora/[install guide].
+
NOTE: As part of Antora installation, you should install site-generator globally.

. Change to the `docs` directory of the repo you want to convert. For some repos, eg `mobile-docs` and `processes`, use the root directory of the repo. 

. Modify the site definition as required. If you are working on a branch, you'll want to specify that branch in the `local-site.yml` file. For example:
+
----
site:
  title: AeroGear
  url: https://www.aerogear.org
  start_page: processes::index
content:
  sources:
  - url: .
    branches: AEROGEAR-2480
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''
    mobile-next: 'AeroGear Mobile Services'
    mobile-client: '{mobile-client} '
ui:
  bundle:
    url: https://github.com/finp/antora-ui/raw/master/build/ui-bundle.zip
    snapshot: true

----

. Run antora:
+
----
antora local-site.yml
----

If you encounter a libcurl error on linux, follow the Option 1 instructions at:
https://docs.antora.org/antora/1.0/install/troubleshoot-nodegit/

== Remote Repos

The following repos are used to publish the documentation:

* mobile-docs
* metrics-apb
* unifiedpush-apb
* aerogear-digger-apb
* keycloak-apb
* custom-runtime-connector-apb
* aerogear-android-sdk
* aerogear-ios-sdk
* aerogear-js-sdk
* aerogear-xamarin-sdk



