= Mobile Docs

This readme introduces the standards for contributing to AeroGear docs.

The goal of these docs is to help users of AeroGear projects "understand things well and not feel like they're dealing with a capricious minor god instead of a product." footnote:[Laura Bailey]

- If you see an issue in documentation, link:https://github.com/aerogear/mobile-docs/issues/new[raise an issue^] and post a PR with a fix for a review. Include as much information as possible.
- See the link:https://github.com/aerogear/mobile-docs/projects/1[Kanban board^].

:toc: 1

== Writing AeroGear Documentation

- If you make a filename change (for example adding or renaming a file), you must update the appropriate modules/ROOT/nav.adoc file. 
-  Determine which functionality is this documentation related to?
+
* Push
* Metrics
* Common to all mobile services
* Common to all services or SDKs but with some information that is specific to each.
+
With this information, you should be able to determine where the file should be located in the repo, for example `modules/ROOT/push`
+
If you intend to reuse a part of a file, create a partial in modules/ROOT/_partials and refer to it using an `include` directive.

- Stick to present tense, for example `When you add the dashboard, it appears on ...`, not `When you add the dashboard, it will appear on ...`

- Test your changes xref:#using-antora[using Antora]
 
== Structure of AeroGear documentation

Concept::
An introduction to a new term, process, module or component. For example, "Mobile Service" : what is it? why do I care? and how does it fit into my development environment?

* Name file by slugifying title

* Prefix filenames with con_

Procedure::
The important information that gets me using AeroGear software, for example, write your procedure by answering the following questions:
+
. Who should perform this procedure?
. Why am I performing this procedure? benefits or context in a higher level user story
. What is the object of the task? for example adding a dashboard.. to what?
. What do I need to know and/or do before installing or provisioning the software?
. What do I need to do to provision the software?
. What are the minimum configuration tasks that I need to do to get value from the software?
. What additional information would be useful after completing procedure (for example, next steps)

* Name file by slugifying title

* no prefix on filenames

See link:https://redhat-documentation.github.io/modular-docs/#creating-procedure-modules[Creating Procedures]

Reference::
Information I might need to debug or extend the normal usage of AeroGear software. For example:
+
* API syntax and definitions
* Configuration optionss 

* Name file by slugifying title

* Prefix filenames with ref_




== AsciiDoc text document format

"AsciiDoc is a text document format for writing notes, documentation, articles, books, ebooks, slideshows, web pages, man pages and blogs."

See link:http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc syntax quick reference^]:

* Avoid using headings with `--, ~~, ^^, ++`
* Avoid using Markdown
* Try to use syntax highlighting wherever possible, for example `[source, bash]`

== Modular Documentation Templates

See link:https://redhat-documentation.github.io/modular-docs/[Modular Docs].

[[using-antora]]
== Using Antora to convert AsciiCoc to HTML

NOTE: You can avoid using Antora to preview the docs with online tool as described in https://github.com/finp/mobile-netlify

After modifying documentation, validate your changes and preview the results by:

. Installing Antora globally as described in their https://docs.antora.org/antora/1.0/install/install-antora/[install guide].
+
NOTE: As part of Antora installation, you should install site-generator globally.
+
If you encounter a libcurl error on linux, follow the Option 1 instructions at:
https://docs.antora.org/antora/1.0/install/troubleshoot-nodegit/


. Fork this repo and set up origin and upstream remotes.

. Change to the `mobile-docs` directory.

. Run antora:
+
----
./bin/quick-build.sh local-site.yml
----
+
Note: <site-file> refers to either:
+
* local-site - your current directory
* site.yml - the master branch of the github repo
+ 
When building for publication use:
+
----
./bin/build.sh
----
+


NOTE: After changes to link:https://github.com/aerogear/antora-ui[antora-ui], you might need to run 'antora --pull --clean <site-file>' to pick up those changes.


== Editing

After reviewing a rendered html file, you might identify a change. When editing a file, you might find that the content is not in the associated adoc file, because it's rendered by using the asciidoc `include` command. You can edit the included file, but note that editing the source file can have unintended effect. 

For example, when editing the `registering-an-app.adoc`, avoid problems by: 

. Regex search for `include.*registering-an-app` across the whole repo.
. Review the list of files from this search to understand of the context of the content.
. Use your judgement when editing the file to make sure the content is appropriate for each rendering of that content. 


[[publishing]]
== Publishing

. Run antora using following command:
+
----
./bin/build.sh
----

. Review the output (`build\site\index.html`) for errors. Correct if required.
+
NOTE: Check for correct styling changes too.
+
. Make a PR against  https://github.com/aerogear/docs.aerogear.org

NOTE: This repo contains more than just the output of mobile-docs repo. See https://github.com/aerogear/docs.aerogear.org/blob/master/README.adoc for more details.

== References to remote repos

No remote repos were harmed in the production of this documentation ;)

References to code can be included as follows:


1. Decide on a name for the snippet, for example push-ios-register 

2. Create a partial in mobile-docs, for example:
https://github.com/aerogear/mobile-docs/blob/master/modules/ROOT/pages/_partials/push-ios-register.inc

3. Reference the code file you want to use (with a tags filter):
+
----
 include::https://raw.githubusercontent.com/aerogear/ios-showcase-template/push-push/ios-showcase-template/push/PushHelper.swift[tags=push-ios-register]
----

4. Add tags to the code repo, for example: 
+
----
// tag::push-ios-register[]
    public func registerUPS(_ deviceToken: Data) {
        AgsCore.logger.info("Registered for notifications with token")

        var config = UnifiedPushConfig()
        config.alias = "Example App"
        config.categories = ["iOS", "Example"]

        AgsPush.instance.register(
            deviceToken,
            config,
            success: {
                AgsCore.logger.info("Successfully registered to Unified Push Server")
            },
            failure: { (error: Error!) in
                AgsCore.logger.error("Failure to register for on Unified Push Server: \(error)")
            }
        )
    }
// end::push-ios-register[]

----

5. Edit adoc file with the following to display the content:
+
----
 include::{partialsdir}/push-ios-register.inc-rantora.adoc[]
----
+
NOTE: You need to run mobile-docs:/bin/build.sh <site>.yml to make sure the temp files are in place when building site