runtime:
  cache_dir: ./.cache/antora
site:
  title: AeroGear Mobile Services
  url: https://docs.aerogear.org
  start_page: aerogear::getting-started
content:
  sources:
  - url: https://github.com/aerogear/mobile-docs.git
    branches: [master, v2.0]
ui:
  bundle:
    url: https://github.com/aerogear/antora-ui/raw/master/build/ui-bundle.zip
    snapshot: true

asciidoc:
  extensions:
  - ./lib/tab-block.js
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''
    include-tags: !excludeUpstream;!excludeAll
