runtime:
  cache_dir: ./.cache/antora
site:
  title: AeroGear Docs
  url: https://docs.aerogear.org
  start_page: aerogear::index
content:
  sources:
  - url: .
    branches: antora-init
  - url: git@github.com:aerogearcatalog/metrics-apb.git
    branches: AEROGEAR-2475
    start_path: docs
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''
    mobile-next: 'AeroGear Mobile Services'
    mobile-client: 'mobile client '
ui:
  bundle:
    url: https://github.com/finp/antora-ui/raw/master/build/ui-bundle.zip
    snapshot: true

