runtime:
  cache_dir: ./.cache/antora
site:
  title: AeroGear
  url: https://www.aerogear.org
  start_page: aerogear::index
content:
  sources:
  - url: git@github.com:aerogearcatalog/keycloak-apb.git
    branches: master
    start_path: docs
  
  - url: git@github.com:aerogearcatalog/metrics-apb.git
    branches: master
    start_path: docs

  - url: git@github.com:aerogearcatalog/unifiedpush-apb.git
    branches: master
    start_path: docs

  - url: git@github.com:aerogearcatalog/aerogear-digger-apb.git
    branches: master
    start_path: docs

  - url: git@github.com:aerogear/aerogear-android-sdk.git
    branches: master
    start_path: docs

  - url: git@github.com:aerogear/aerogear-js-sdk.git
    branches: master
    start_path: docs

  - url: git@github.com:aerogear/aerogear-xamarin-sdk.git
    branches: master
    start_path: docs

  - url: git@github.com:aerogear/aerogear-ios-sdk.git
    branches: master 
    start_path: docs

  - url: .
    branches: master
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''
    mobile-next: 'AeroGear Mobile Services'
    mobile-client: '{mobile-client} '
ui:
  bundle:
    url: https://github.com/aerogear/antora-ui/raw/master/build/ui-bundle.zip
    snapshot: true

