:org: AeroGear
//source: https://github.com/aerogear/minishift-mobilecore-addon/blob/master/README.md


[[setting-up-minishift]]
= Setting up Minishift

. link:https://docs.openshift.org/latest/minishift/getting-started/installing.html[Install Minishift]
+
Check Minishift version is at least 1.11.0:
+
[source,bash]
----
$ minishift version
minishift v1.11.0+4459917
----

. link:https://docs.openshift.org/latest/cli_reference/get_started_cli.html#installing-the-cli[Install OC]

. Enable Minishift experimental addons:
+
[source,bash]
----
export MINISHIFT_ENABLE_EXPERIMENTAL=y
----

. Clone the link:https://github.com/aerogear/minishift-mobilecore-addon[minishift-mobilecore-addon] repo.


. Add minishift-mobilecore to the minishift add-ons catalog:
+
[source,bash]
----
minishift addon install -f minishift-mobilecore-addon/
minishift addons enable mobilecore
----

. Set the following environment variables, replacing `aerogearcatalog` with your own Dockerhub organization if required:
+
[source,bash]
----
export DOCKERHUB_USERNAME=<docker hub username>
export DOCKERHUB_PASSWORD=<docker hub password>
export DOCKERHUB_ORG=aerogearcatalog
----

. Configure Minishift for AeroGear:
+
[source,bash]
----
minishift config set addon-env DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME},DOCKERHUB_PASSWORD="${DOCKERHUB_PASSWORD}",DOCKERHUB_ORG=${DOCKERHUB_ORG}
----

. Configure Minishift resources
+
{Org} recommends configuring Minishift to start with extra CPUs and RAM:
+
[source,bash]
----
minishift config set cpus 4
minishift config set memory 4096
----

. Clear Minishift to enable mobile core:
+
[source,bash]
----
minishift stop
minishift delete
----

. Create a new Minishift cluster with service catalog and mobile core:
+
[source,bash]
----
minishift start --openshift-version 3.7.0 --service-catalog
----
+
If you did not enable the addon, you need to apply it manually:
+
[source,bash]
----
minishift addons apply mobilecore
----

== Troubleshooting

. Try resolving the issue by deleting the Minishift VM and restarting:
+
[source,bash]
----
minishift stop
minishift delete
minishift start --openshift-version 3.7.0 --service-catalog
----

. Confirm the addon-env config values are correct:
+
[source,bash]
----
minishift config get addon-env
----
+
If values are incorrect, follow the instructions in xref:setting-up-minishift[Setting up Minishift].

. Review the following scenarios:
+
* xref:service-catalog-not-recognized[]
* xref:mobile-tab-not-appearing[]
* xref:apbs-not-showing[]
* xref:errors-when-stopping[]


[[service-catalog-not-recognized]]
.Service catalog flag is not recognized
This is an error output by Minishift when it is running without the `MINISHIFT_ENABLE_EXPERIMENTAL` environment variable set to 'y'. To correct this run the following in your current shell:

----
export MINISHIFT_ENABLE_EXPERIMENTAL=y
----
[[mobile-tab-not-appearing]]
.Mobile tab not appearing in the service catalog

. Make sure the Ansible Service Broker is running:
+
.. Log into your Minishift cluster as admin:
+
[source,bash]
----
oc login -u system:admin
----

.. Check that the asb pod is running correctly in the `ansible-service-broker` namespace:
+
[source,bash]
----
oc get pods -n ansible-service-broker
----
+
If the asb pos is running correctly, you see something similar to the following:
+
[source,bash]
----
NAME               READY     STATUS    RESTARTS   AGE
asb-1-8n4b6        1/1       Running   0          46m
asb-etcd-1-ptzmp   1/1       Running   0          46m
----

.. If the asb pods are not running, start them using either of the following commands:
+
[source,bash]
----
oc rollout latest asb
oc rollout latest asb-etcd
----

. Make sure the Ansible Service Broker can find the Mobile APBs by following the procedure in xref:apbs-not-showing[]

[[apbs-not-showing]]
.APBs not displayed in service catalog

This issue is typically caused by incorrect values for the DOCKERHUB_USER, DOCKERHUB_PASSWORD or DOCKERHUB_ORG.

To check the values:

[source,bash]
----
minishift config get addon-env
----

After correcting any values, you need to delete and restart the Minishift VM:

[source,bash]
----
minishift stop
minishift delete
minishift start --openshift-version 3.7.0 --service-catalog
----

[[errors-when-stopping]]
.Errors displayed when stopping or deleting Minishift

. Check any links to Minishift documentation displayed in the errors.

. Check the Minishift configuration, typically `~/.minishift` for any possible permission issues. 

. Try running `minishift stop` and retrying `minishift delete`. 

. If the issue is still occurring, delete the Minishift configuration directory and recreate it:
+
[source,bash]
----
sudo rm -rf ~/.minishift
minishift addons install -f /path/to/minishift-mobilecore-addon
minishift addons enable mobilecore
----

