include::{partialsdir}/attributes.adoc[]

= Performing Device Trust Checks in your Device

This section describes what Device Trust Checks are available and how to execute them for the supported platforms. Also, mind that Security Checks can be performed either individually or together.

NOTE: A *successful* check means that the environment the application is running in is more secure and no action is required, as opposed to signalling if a certain feature is enabled.
For example, the `Root Access Detection Check NOT_ROOTED` should return `true` when it is _not rooted_, since this would be the more secure condition.





== Root Access Detection

Use this to help prevent your app running in a device that has been rooted/jailbroken.

[role="primary"]
.Android
****
[source,java]
----
SecurityService securityService = MobileCore.getInstance(SecurityService.class);

SecurityCheckResult result = securityService.check(SecurityCheckType.NOT_ROOTED);
----
****


== Developer Mode Detection

Use this to detect if Developer Mode has been enabled on the device.

[role="primary"]
.Android
****
[source,java]
----
SecurityService securityService = MobileCore.getInstance(SecurityService.class);

SecurityCheckResult result = securityService.check(SecurityCheckType.NO_DEVELOPER_MODE);
----
****


== Debugger Detection

Use this to detect if an Android debugger is attached to the app.

[role="primary"]
.Android
****
[source,java]
----
SecurityService securityService = MobileCore.getInstance(SecurityService.class);

SecurityCheckResult result = securityService.check(SecurityCheckType.NO_DEBUGGER);
----
****


== Emulator Detection

Use this to detect if the app is being run on an emulator.

[role="primary"]
.Android
****
[source,java]
----
SecurityService securityService = MobileCore.getInstance(SecurityService.class);

SecurityCheckResult result = securityService.check(SecurityCheckType.NOT_IN_EMULATOR);
----
****


== Device Lock Detection

Use this to detect if a device has a lock screen set (with pin, fingerprint, pattern...).

[role="primary"]
.Android
****
[source,java]
----
SecurityService securityService = MobileCore.getInstance(SecurityService.class);

SecurityCheckResult result = securityService.check(SecurityCheckType.SCREEN_LOCK_ENABLED);
----
****


== App Data Backup Detection

Use this to detect whether the application’s data is configured to be synchronized across devices.

[role="primary"]
.Android
****
[source,java]
----
SecurityService securityService = MobileCore.getInstance(SecurityService.class);

SecurityCheckResult result = securityService.check(SecurityCheckType.ALLOW_BACKUP_DISABLED);
----
****


== Device Encryption Detection

Use this to detect whether the devices filesystem is encrypted.

[role="primary"]
.Android
****
[source,java]
----
SecurityService securityService = MobileCore.getInstance(SecurityService.class);

SecurityCheckResult result = securityService.check(SecurityCheckType.HAS_ENCRYPTION_ENABLED);
----
****






== Invoking Multiple Self Defence Checks

Security Checks can be run in group, both synchronously and asynchronously.

=== Synchronously

[role="primary"]
.Android
****

To run multiple self defence checks synchronously, you’ll first need to invoke the SecurityService#getCheckExecutor method. This methods returns SyncSecurityCheckExecutor where checks can be added (chained) to the executor and executed synchronously.

[source,java]
----
SecurityService securityService = MobileCore.getInstance(SecurityService.class);

SyncSecurityCheckExecutor syncCheckExecutor = securityService.getCheckExecutor();
Map<String, SecurityCheckResult> results = syncCheckExecutor
    .addCheck(SecurityCheckType.<check_type>)
    // Add more checks here
    .execute();
----
****

=== Asynchronously

[role="primary"]
.Android
****
[source,java]
----
SecurityService securityService = MobileCore.getInstance(SecurityService.class);

AsyncSecurityCheckExecutor asyncCheckExecutor = securityService.getAsyncCheckExecutor();
Map<String, Future<SecurityCheckResult>> results = asyncCheckExecutor
    .addCheck(SecurityCheckType.<check_type>)
    // Add more checks here
    .execute();
----
****





== Additional Resources

=== Adding Custom Self Defence Checks

Besides the xref:security/index.adoc#ref_terminology_Device%20Security_ref_terminology[Provided Self Defence Checks] it's also possible to make use of your own custom checks. Follow the next steps depending on your platform to implement them:

[role="primary"]
.Android
****

. Extend the `AbstractSecurityCheck` interface:
+
[source,java]
----
class CustomSecurityCheck extends AbstractSecurityCheck {

    @Override
    protected boolean execute(@NonNull final Context context) {
        // Implement security check logic here and return result
        return false;
    }

}
----

. Instantiate it to execute it, using the instance of `SecurityService`:
+
[source,java]
----
SecurityService securityService = MobileCore.getInstance(SecurityService.class);

SecurityCheck customSecurityCheck = new CustomSecurityCheck();
SecurityCheckResult result = securityService.check(customSecurityCheck);
----
+
Alternatively, you can add it to an existing `AsyncCheckExecutor` or `SyncCheckExecutor`:
+
[source,java]
----
SecurityService securityService = MobileCore.getInstance(SecurityService.class);

AsyncSecurityCheckExecutor asyncCheckExecutor = securityService.getAsyncCheckExecutor();
asyncCheckExecutor.addCheck(new customSecurityCheck());
----
****





=== Reporting Self Defence Checks Results Via the Metrics Service

[role="primary"]
.Android
****
In order to report the results of Self Defence utilize this service in conjunction with the xref:metrics/index.adoc[Metrics].

Individual checks can be reported via the `checkAndSendMetric` method:

[source, java]
----
MetricsService metricsService = MobileCore.getInstance(MetricsService.class);
SecurityService securityService = MobileCore.getInstance(SecurityService.class);

SecurityCheckResult result = securityService.checkAndSendMetric(SecurityCheckType.<check_type>, metricsService);
----

Reporting the results for multiple checks can be done via an `Executor` that is passed a reference to the `MetricsService`:

[source, java]
----
MetricsService metricsService = mobileCore.getInstance(MetricsService.class);
Map<String, SecurityCheckResult> results = SecurityCheckExecutor.Builder.newSyncExecutor(this.getContext())
    .withSecurityCheck(SecurityCheckType.<check_type>)
    // Add other checks...
    .withMetricsService(metricsService)
    .build()
    .execute();
----
****