[[using-self-signed-certificates-in-mobile-clients]]
== Using Self-Signed Certificates in Mobile Clients

Throughout the development lifecycle of a mobile applications, a common
requirement is often the need to integrate and connect with some backend
services, often in a secure manner. However in order for the client
device to connect over SSL/TLS, it will need to trust the root
certificate authority. This cert must be installed on the client device
to ensure that the client trusts server certificates that are signed by
the CA.

When the certificate is using a trusted root CA this is not an issue and is done automatically.
In a development environment, such as a local OpenShift cluster which uses
self-signed certificates, this is not the case. However we have the
ability to easily extract the root certificate from the cluster allowing
us to install it on the device and mark it as trusted, allowing our
application and/or web browser to connect over a secure layer.

[[extracting-root-ca]]
== Extracting Root CA
The simplest method for extracting the required root certificate is to
query the API server for the OpenShift routers secret and parse the
result. The following command, which parses the response and saves it to
a file `localcluster.crt` in the `/tmp` directory should be run as
`system:admin` user.

[source,bash]
----
oc get secret router-certs --template='{{index .data "tls.crt"}}' -n default  |  \
base64 --decode | sed -e '1,/^-----END RSA PRIVATE KEY-----$/ d'  > /tmp/localcluster.crt
----

[[installing-on-device]]
== Installing on Device
Once the certificate file has been created, follow the instructions
below for the required device type. For both device types, a pin should
be configured to ensure the certificate can be installed.

Various methods can be used to **get the certificate to the device**.

* USB *(Android only)* - Attach the device to the machine hosting
OpenShift via USB and drag the certificate to the devices file system
* Email attachment - Simply email the certificate to an address
accessible from the device and download the attachment.
* Cloud service - Use a cloud storage service such as Dropbox or Google
Drive which is accessible from the device, browse to the certificate and
proceed to download it.
* Local file server - **Both device and OpenShift cluster will need to
be on the same network for the following to work**. On the machine which
is running the OpenShift cluster, browse to the directory where the
certificate exists and start a temporary web server:
[source,bash]
----
   #Python 2 python -m SimpleHTTPServer
   #Python 3 python3 -m http.server
----
Browse to the address of the OpenShift host at port `8000` and proceed
to download the certificate. Close the web server.

[role="primary"]
.Android

****
Go to Settings > Security > Install from storage. It should detect the
certificate and let you add it to the device.
****

[role="secondary"]
.iOS

****
When you download the certificate using any of the methods above, the
device should automatically detect a profile. Simply follow the on
screen instructions to install it.

Versions iOS 10.3 and later require an additional step to trust the now
installed certificate. Instructions can be found on the
https://support.apple.com/en-us/HT204477[Apple support site]
****
