include::{partialsdir}/attributes.adoc[]

= Performing Device Trust Checks in your Device

== Invoking a Single Check

[role="primary"]
.Android
****
The `SecurityService#check` method can be used to run a single self defence check. It expects either `SecurityCheckType` or `SecurityCheck` as a parameter and returns `SecurityCheckResult`.

[source,java]
----
SecurityCheckResult result = securityService.check(SecurityCheckType.<check_type>);
----

== Invoking Multiple Checks

To invoke multiple self defence checks a security check executor must be used.  There are two types of security check executors: link:javadoc[`SyncSecurityCheckExecutor`], where self defence checks are executed synchronously, and link:javadoc[`AsyncSecurityCheckExecutor`], where self defence checks are executed asynchronously.

=== Synchronously

To run multiple self defence checks _synchronously_, you'll first need to invoke the link:javadoc[`SecurityService#getCheckExecutor`] method.  This methods returns link:javadoc[`SyncSecurityCheckExecutor`] where checks can be added (chained) to the executor and executed synchronously.


[source, java]
----
SyncSecurityCheckExecutor syncCheckExecutor = securityService.getCheckExecutor();
----

=== Asynchronously

To run multiple self defence checks _asynchronously_, you’ll first need to invoke the link:javadoc[`SecurityService#getAsyncCheckExecutor`] method. This methods returns link:javadoc[`AsyncSecurityCheckExecutor`] where checks can be added (chained) to the executor and executed asynchronously.

[source, java]
----
AsyncSecurityCheckExecutor asyncCheckExecutor = securityService.getAsyncCheckExecutor();
----

=== Adding Checks to Self Defence Check Executors

Both the link:javadoc[`SyncSecurityCheckExecutor`] and link:javadoc[`AsyncSecurityCheckExecutor`] have an `addCheck` method.  This method expects either link:javadoc[`SecurityCheckType`]  or link:javadoc[`SecurityCheck`] as a paramater. +

If you are invoking the `addCheck` method on a link:javadoc[`SyncSecurityCheckExecutor`] then it will return link:javadoc[`SyncSecurityCheckExecutor`]. +

If you are invoking the `addCheck` method on an link:javadoc[`AsyncSecurityCheckExecutor`] then it will return link:javadoc[`AsyncSecurityCheckExecutor`].

[source, java]
----
// adding self defence checks to a SyncSecurityCheckExecutor

// add two provided self defence checks to the syncCheckExecutor
syncCheckExecutor.addCheck(SecurityCheckType.<check_type>).addCheck(SecurityCheckType.<check_type>);
// add the CustomSecurityCheck to the syncCheckExecutor
syncCheckExecutor.addCheck(new customSecurityCheck());


// adding self defence checks to a AsyncSecurityCheckExecutor

// add two provided self defence checks to the asyncCheckExecutor
asyncCheckExecutor.addCheck(SecurityCheckType.<check_type>).addCheck(SecurityCheckType.<check_type>);
// add the CustomSecurityCheck to the asyncCheckExecutor
asyncCheckExecutor.addCheck(new customSecurityCheck());
----

=== Executing Self Defence Checks on Executors

Both link:javadoc[`SyncSecurityCheckExecutor`] and link:javadoc[`AsyncSecurityCheckExecutor`] have an `execute` method that executes all self defence checks that have been added. +

The `execute` method for link:javadoc[`SyncSecurityCheckExecutor`] returns a `Map` where the key is the name of the self defence check being tested (`String`) and the value is  link:javadoc[`SecurityCheckResult`]. +

The `execute` method for link:javadoc[`AsyncSecurityCheckExecutor`] returns a `Map` where the key is the result of the `getName` method on the `SecurityCheck` instance being tested and the value is a `Map` of type `Future` with link:javadoc[`SecurityCheckResult`].

[source, java]
----
// execute self defence checks on the syncCheckExecutor
Map<String, SecurityCheckResult> results = syncCheckExecutor.execute();

// execute self defence checks on the asyncCheckExecutor
Map<String, Future<SecurityCheckResult>> results = asyncCheckExecutor.execute();
----

Both link:javadoc[`SyncSecurityCheckExecutor`] and link:javadoc[`AsyncSecurityCheckExecutor`] allow for multiple checks to be chained so the above examples can be refactored to:

[source, java]
----
// adding self defence checks and executing these checks synchronously
Map<String, SecurityCheckResult> results = securityService.getCheckExecutor().addCheck(new customSecurityCheck()).addCheck(SecurityCheckType.<check_type>).addCheck(SecurityCheckType.<check_type>).execute();

// adding self defence checks and executing these checks asynchronously
Map<String, Future<SecurityCheckResult> results = securityService.getAsyncCheckExecutor().addCheck(new customSecurityCheck()).addCheck(SecurityCheckType.<check_type>).addCheck(SecurityCheckType.<check_type>).execute();
----
****

== Adding Custom Self Defence Checks

Besides the xref:security/index.adoc#ref_terminology_Device%20Security_ref_terminology[Provided Self Defence Checks] it's also possible to make use of your own custom checks. Follow the next steps depending on your platform to implement them:

[role="primary"]
.Android
****

Extend the `AbstractSecurityCheck` interface:

[source,java]
----
class CustomSecurityCheck extends AbstractSecurityCheck {

    /**
     * Custom security check.
     *
     * @param context Context to be used by the check.
     * @return <code>true</code> or <code>false</code>
     */
    @Override
    protected boolean execute(@NonNull final Context context) {
        // Implement security check in customSecurityCheck()
        boolean result = customSecurityCheck();
        return result;
    }

}
----
****

== Additional Resources

=== Reporting Self Defence Checks Results Via the Metrics Service

[role="primary"]
.Android
****
In order to report the results of Self Defence utilize the link:./metrics[Metrics] service in conjunction with the link:javadoc[SecurityService].

Individual checks can be reported via the `checkAndSendMetric` method:

[source, java]
----
MetricsService metricsService = mobileCore.getInstance(MetricsService.class);
SecurityService securityService = activity.mobileCore.getInstance(SecurityService.class);
SecurityCheckResult result = securityService.checkAndSendMetric(SecurityCheckType.<check_type>, metricsService);
----

Reporting the results for multiple checks can be done via an `Executor` that is passed a reference to the `MetricsService`:

[source, java]
----
MetricsService metricsService = mobileCore.getInstance(MetricsService.class);
Map<String, SecurityCheckResult> results = SecurityCheckExecutor.Builder.newSyncExecutor(this.getContext())
    .withSecurityCheck(SecurityCheckType.<check_type>)
    // other checks...
    .withMetricsService(metricsService)
    .build().execute();
----
****