include::{partialsdir}/attributes.adoc[]

//':context:' is a vital parameter. See: http://asciidoctor.org/docs/user-manual/#include-multiple
:context: ref_terminology_{device-security-service}

[id='{context}_ref_terminology']

= Provided Self Defence Checks

The following are the self defence checks provided by the SDK.

NOTE: A *successful* check means that the environment the application is running in is more secure and no action is required, as opposed to signalling if a certain feature is enabled.
For example, the `Root Access Detection Check NOT_ROOTED` should return `true` when it is _not rooted_, since this would be the more secure condition.

Root Access Detection (NOT_ROOTED)::
To help prevent your app running in a device that has been rooted/jailbroken the `SecurityCheckType#NOT_ROOTED` function can be used. This function uses the link:https://github.com/scottyab/rootbeer[Rootbeer] library to check if root access is present on the device.

Developer Mode Detection (NO_DEVELOPER_MODE)::
To detect if Developer Mode has been enabled on the device the `SecurityCheckType#NO_DEVELOPER_MODE` function can be used. This function uses Android’s link:https://developer.android.com/reference/android/provider/Settings.html[`Settings`] class.

Debugger Detection (NO_DEBUGGER)::
To detect if an Android debugger is attached to the app the `SecurityCheckType#NO_DEBUGGER` function can be used. This function uses Android’s link:https://developer.android.com/reference/android/os/Debug.html[`Debug`] class.

Emulator Detection (NOT_IN_EMULATOR)::
To detect if the app is being run on an emulator the `SecurityCheckType#NOT_IN_EMULATOR` function can be used. This function uses Android’s link:https://developer.android.com/reference/android/os/Build.html[`Build`] class.

Device Lock Detection (SCREEN_LOCK_ENABLED)::
To detect if a device has a lock screen set (with pin, fingerprint, pattern) the `SecurityCheckType#SCREEN_LOCK_ENABLED` function can be used. This function uses Android’s link:https://developer.android.com/reference/android/app/KeyguardManager.html[`KeyguardManager`] class.

App Data Backup Detection (ALLOW_BACKUP_DISABLED)::
To detect whether the application’s data is configured to be synchronized across devices the `SecurityCheckType#ALLOW_BACKUP_DISABLED` function can be used. The link:https://developer.android.com/guide/topics/manifest/application-element.html[`allowBackup`] flag determines whether to allow the application to participate in the backup and restore infrastructure, which might be interesting to avoid depending on your app’s needs.

Device Encryption Detection (HAS_ENCRYPTION_ENABLED)::
To detect whether the devices filesystem is encrypted the `SecurityCheckType#HAS_ENCRYPTION_ENABLED` function can be used. This function uses Android’s link:https://developer.android.com/reference/android/app/admin/DevicePolicyManager.html[`DevicePolicyManager`] class.