= AeroGear Services Security SDK
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:
:toc-placement!:

toc::[]

The security SDK provides security features such as self defence checks to ensure that the device where the application is running is trusted.

== Prerequisites

To use the Security SDK you will first need to:

* Import the link:https://github.com/aerogear/aerogear-xamarin-sdk/blob/master/docs/modules/getting-started/pages/core.adoc[Core module]
* Import your platform specific Security module (`Security.iOS` or `Security.Android`)

== Self Defence Checks

As part of the Security SDK module, there is a self defence check feature that will make sure that yor application is meeting the modern OWASP recommendations.  This feature offers multiple security checks that can be used to analyse the security of the device.  This can be useful for developers to detect vulnerablities and react accordingly.  For example, if the app detects security issue *X* then do *Y*, where *X* could be no lock screen is set and *Y* is show a system prompt to setup the lock screen.

=== Usage

To begin using self defence checks in your app, you'll need to retrieve an instance of `SecurityService`. The `SecurityService` can be retrieved using the `MobileCore#GetService` method.

[source, c#]
----
var SecurityService = MobileCore.GetService<SecurityService>();
----

Any subsequent `MobileCore#GetService` method will return the same instance of `SecurityService`. +
Self defense checks can either be <<Provided Self Defence Checks,provided>> by the SDK or <<Custom Self Defence Checks,custom>>.

=== Provided Self Defence Checks

The Security SDK provides a set of common self defence checks enlisted into the `SecurityChecks` class.

A successful check means that the environment the application is running in is secure and no action is required, as opposed to signalling if a certain feature is enabled.

For example, the Emulator Detection Check `NOT_IN_EMULATOR` will return `true` when the app is *not* running in an emulator, since this would be the more secure condition.

Many of the checks are cross platform, however some of them are platform specific (for example, NOT_ROOTED is for android, while NOT_JAILBROKEN is for iOS).

==== Root Access Detection (NOT_ROOTED)

IMPORTANT: This check is available for Android only

To help prevent your app running in a device that has been rooted the `SecurityChecks#NOT_ROOTED` check can be used.
A device is considered rooted if *any* of the following are true:

* A custom key has been used to sign the kernel
* The `su` binaries are present

==== Jailbreak Detection (NOT_JAILBROKEN )

IMPORTANT: This check is available for iOS only

To help prevent your app running in a device that has been rooted the `SecurityChecks#NOT_JAILBROKEN` check can be used.
A device is considered JAILBROKEN if *any* of the following are true:

* /Applications/Cydia.app exists
* /Library/MobileSubstrate/MobileSubstrate.dylib exists
* /bin/bash exists
* /usr/sbin/sshd exists
* /etc/apt exists
* /private/var/lib/apt/ exists
* Applications exists that can handle the "cydia://package/com.example.package" URL

==== Developer Mode Detection (NO_DEVELOPER_MODE)

IMPORTANT: This check is available for Android only

To detect if Developer Mode has been enabled on the device the `SecurityChecks#NO_DEVELOPER_MODE` check can be used.
This check uses Android's link:https://developer.xamarin.com/api/type/Android.Provider.Settings+Global/[Settings.Global] class.

==== Debugger Detection (NO_DEBUGGER)

To detect if the application is running in Debug Mode, `SecurityChecks#NO_DEBUGGER` function can be used.

[NOTE]
====
[horizontal]
ANDROID:: Uses the Android's link:https://developer.xamarin.com/api/type/Android.OS.Debug/[Debug] class.
iOS:: Uses the iOS link:https://docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.Debugger/[Debugger] class
====

==== Emulator Detection (NOT_IN_EMULATOR)

To detect if the app is being run in an emulator the `SecurityChecks#NOT_IN_EMULATOR` function can be used.

[NOTE]
====
[horizontal]
ANDROID:: Uses the Android's link:https://developer.xamarin.com/api/type/Android.OS.Build/[Build] class.
iOS:: Uses the iOS link:https://developer.xamarin.com/api/field/ObjCRuntime.Runtime.Arch/[Arch] class
====

==== Device Lock Detection (SCREEN_LOCK_ENABLED)

To detect if a device has a lock screen set (with pin, fingerprint, pattern) the `SecurityChecks#SCREEN_LOCK_ENABLED` function can be used.

[NOTE]
====
[horizontal]
ANDROID:: Uses the Android's link:https://developer.xamarin.com/api/type/Android.App.KeyguardManager[KeyguardManager] class.
iOS:: Uses the iOS link:https://developer.xamarin.com/api/type/MonoTouch.LocalAuthentication.LAContext/[LAContext] class
====

==== App Data Backup Detection (ALLOW_BACKUP_DISABLED)

IMPORTANT: This check is available for Android only

To detect whether the application’s data is configured to be synchronized across devices the `SecurityChecks#ALLOW_BACKUP_DISABLED` function can be used.
The link:https://developer.android.com/guide/topics/manifest/application-element[allowBackup] flag determines whether to allow the application to
participate in the backup and restore infrastructure, which might be interesting to avoid depending on your app’s needs.

==== Device Encryption Detection (HAS_ENCRYPTION_ENABLED)
IMPORTANT: This check is available for Android only

To detect whether the devices filesystem is encrypted the `SecurityChecks#HAS_ENCRYPTION_ENABLED` function can be used.
This function uses Android’s link:https://developer.xamarin.com/api/type/Android.App.Admin.DevicePolicyManager/[DevicePolicyManager] class.

=== Custom Self Defence Checks

These are self defence checks that you can define to be used by the SDK. Custom self defence checks must implement the `ISecurityCheck` interface.

[source, c#]
----
class CustomSecurityCheck : ISecurityCheck
{
	public string GetName()
	{
		return "Custom check";
	}

	public string GetId()
	{
		return typeof(CustomSecurityCheck).FullName;
	}

	public SecurityCheckResult Check()
	{
		// In this example, the check always passes...
		return new SecurityCheckResult(this, true);
	}
}
----

=== Invoking a Single Self Defence Check
The `SecurityService#Check` method can be used to run a single self defence check.  It expects either `SecurityChecks` (see <<Provided Self Defence Checks>>)
or `ISecurityCheck` (see <<Custom Self Defence Checks>>) as a parameter and returns `SecurityCheckResult`.

[source, c#]
----
// a provided self defence check
SecurityCheckResult result = securityService.Check(SecurityChecks.<check_type>);

// using the custom self defence check defined previously
ISecurityCheck customSecurityCheck = new CustomSecurityCheck();
SecurityCheckResult result = securityService.Check(customSecurityCheck);
----

=== Invoking Multiple Self Defence Checks

To invoke multiple self defence checks a security check executor must be used. To run multiple self defence checks synchronously, you'll need to invoke `SecurityService#GetSyncExecutor`.
The returned object will be a builder that will allow to configure the list of checks to be executed. That list can be a mix of checks provided by the SDK and
custom checks.

[source, c#]
----
Dictionary<string, SecurityCheckResult> results = securityService.GetSyncExecutor()
								.WithSecurityCheck(SecurityChecks.<check_type>)
								.WithSecurityCheck(new CustomSecurityCheck())
								.WithSecurityCheck(...)
								...
								...
								.Build()
								.Execute();

----

The `Builder.WithSecurityCheck` method can be invoked as much as needed to add checks to be executed.
The value returned by the `Execute` method will be a `Dictionary` whose value is the result of the check, while the key is the ID of the check that produced that result.
