include::{partialsdir}/attributes.adoc[]

= Adding User Authentication to your Mobile App

This section describes how to perform user authentication for the supported platforms. On authentication a browser window will open and prompt the user for login credentials.

== Implementing authentication

The following examples show how to implement authentication using the Aerogear SDK on all the supported platforms.

[role="primary"]
.Android
****

. Provide an implementation of `Callback` which is defined in the Aerogear SDK and used to handle asynchronous results:
+
[source,java]
----
Callback authCallback = new Callback<UserPrincipal>() {
    @Override
    public void onSuccess(UserPrincipal principal) {
        ...
    }

    @Override
    public void onError(Throwable error) {
        ...
    }
};
----

. Use the instance of the `AuthService` and use the `login` method to hand over to the login browser:
+
[source,java]
----
// Build the options object and start the authentication flow
DefaultAuthenticateOptions options = new DefaultAuthenticateOptions(myActivity, LOGIN_RESULT_CODE);
// authService already initialized
authService.login(options, authCallback);
----

. Override `onActivityResult` to handle the result from the browser. It's important to pass the intent back to the Auth service:
+
[source,java]
----
@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {
    if (requestCode == LOGIN_RESULT_CODE) {
        authService.handleAuthResult(data);
    }
}
----
+
NOTE: This handler should always invoke `handleAuthResult`, providing the `Intent`. This will exchange the temporary tokens returned from `login` for long-lived tokens and will provide a `UserPrincipal` which can be used to access a users details. If this is not invoked you will not have access to the `UserPrincipal`.

. The callback provided to `login` will be invoked.
****

[role="secondary"]
.iOS
****
. Use the `login` method to hand over to the login browser:
+
[source,swift]
----
AgsAuth.instance.login(presentingViewController: self, onCompleted: onLoginComplete)

func onLoginComplete(user: User?, err: Error?) {
    if let error = err {
        return
    }

    let currentUser = user
}
----

. Allow your application to handle the redirect in `AppDelegate`:
+
[source,swift]
----
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey: Any] = [:]) -> Bool {
    do {
        return try AgsAuth.instance.resumeAuth(url: url as URL)
    } catch AgsAuth.Errors.serviceNotConfigured {
        print("AeroGear auth service is not configured")
    } catch {
        fatalError("Unexpected error: \(error).")
    }
    return false
}
----
****

[role="secondary"]
.Cordova
****
Authentication will be performed on initialization as described xref:keycloak/coding.adoc#initializing-the-sdk[here]. To manually redirect to the login screen, use:
[source,javascript]
----
authService.login().then(() => {
    // Login success
}).catch(() => {
    // Login error
});;
----
****

[role="secondary"]
.Xamarin
****
. Use the `Authenticate` method to hand over to the login browser:
+
[source,csharp]
----
IAuthService authService = MobileCore.Instance.GetService<IAuthService>();

var authOptions = DependencyService.Get<IAuthenticateOptionsProvider>().GetOptions();
authService.Authenticate(authOptions).ContinueWith(user =>
{
    // Get the authenticated User from the provided Task.
    Console.WriteLine(user.Result);

    // Change view to user details. No need to handle the user result here, it will be available through
    // authService.CurrentUser()
    Device.BeginInvokeOnMainThread(() => ((RootPage)(App.Current.MainPage)).ChangePage(new UserDetails()));
});
----
****

== Adding Log Out Option to your Mobile App

The following section describes how to perform a logout.

[role="primary"]
.Android
****

. Use the instance of the `AuthService` and retrieve the current user:
+
[source,java]
----
// authService already initialized
UserPrincipal currentUser = authService.currentUser();
----

. Implement `Callback` and call `logout`:
+
[source,java]
----
authService.logout(currentUser, new Callback<UserPrincipal>() {
    @Override
    public void onSuccess() {
        // User Logged Out Successfully and local Auth tokens were Deleted
    }

    @Override
    public void onError(Throwable error) {
        // An error occurred during logout
    }
});
----
****

[role="secondary"]
.iOS
****
. Implement the logout callback:
+
[source,swift]
----
func onLogoutComplete(_: Error?) {
    ...
}
----

. Call `logout` and pass the callback:
+
[source,swift]
----
do {
    try AgsAuth.instance.logout(onCompleted: self.onLogoutComplete)
} catch {
    fatalError("Error logging out: \(error).")
}
----


****

[role="secondary"]
.Cordova
****

To logout invoke the `logout` function:

[source,javascript]
----
authService.logout().then(() => {
    // When the logout succeeded the local tokens obtained during authentication are deleted
});
----

****

[role="secondary"]
.Xamarin
****
To logout invoke the `Logout` method:
[source,csharp]
----
var authService = MobileCore.Instance.GetService<IAuthService>();
authService.Logout(authService.CurrentUser()).ContinueWith(result =>
{
    Device.BeginInvokeOnMainThread(() => ((RootPage)(App.Current.MainPage)).ChangePage(new GoodbyePage()));
});
----
****

NOTE: To perform *backchannel or federated logouts*, you must enable the Backchannel Logout option for the federated identity provider. More information is available in the Keycloak documentation under link:https://www.keycloak.org/docs/3.3/server_admin/topics/identity-broker/oidc.html[OICD Identity Providers, window="_blank"].

[discrete]
== Additional Information

* xref:keycloak/android-additional-configuration.adoc[Additional configuration for Android]

* link:https://www.keycloak.org/docs/3.3/server_admin/topics/identity-broker/oidc.html[Keycloak OICD Providers, window="_blank"]
