include::{partialsdir}/attributes.adoc[]

include::./configuring-dev-env-keycloak.adoc[]

== Setting up {keycloak-service} service SDK

This guide will help you to set up the {keycloak-service} service SDK in your App.

=== Prerequisites

* [x] xref:keycloak/provisioning.adoc[Provisioned {keycloak-service} service].
* [x] xref:keycloak/binding.adoc[Binding] created.
* [x] xref:keycloak/configuring-dev-env-keycloak.adoc[Configured dev environment].
* [x] Read the xref:configuring-dev-env.adoc[general app setup guide].

=== Importing the libraries

[role="primary"]
.Android
****
. Add the following dependency in your app's *build.gradle*:
+
[source,groovy,subs="attributes"]
----
dependencies {
    implementation "org.aerogear:android-auth:{release-number}"
}
----
****

[role="secondary"]
.iOS
****
. Add the dependency to your *Podfile*:
+
[source,ruby,subs="attributes"]
----
target '[TARGET NAME]' do
    pod 'AGSAuth', '{release-number}'
end
----

. Update the dependencies:
+
[source,bash]
----
$ pod install
----

. Import and instantiate `AGSAuth` to start using the SDK:
+
[source,swift]
----
import AGSAuth

let auth = AGSAuth()
----
****

[role="secondary"]
.Cordova
****
Install the link:https://www.npmjs.com/package/@aerogear/auth[AeroGear Auth] package from link:https://www.npmjs.com/[NPM]:
[source,bash]
----
$ npm install @aerogear/auth
----
****

[role="secondary"]
.Xamarin
****
. Install link:https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools[NuGet].

. Install the link:https://www.nuget.org/packages/AeroGear.Mobile.Core[AeroGear Core] package:
+
[source,bash,subs="attributes"]
----
dotnet add package AeroGear.Mobile.Core --version {release-number}
----

. For Android run:
+
[source,bash,subs="attributes"]
----
dotnet add package AeroGear.Mobile.Core.Platform.Android --version {release-number}
----

. For iOS run:
+
[source,bash,subs="attributes"]
----
dotnet add package AeroGear.Mobile.Core.Platform.iOS --version {release-number}
----
****

== Initializing the SDK

[role="primary"]
.Android
****

. Retrieve the auth service:
+
[source,java]
----
AuthService authService = MobileCore.getInstance().getService(AuthService.class);
----

. Specify the redirect URL. It is recommended to use the package name of your app.
+
----
AuthServiceConfiguration authServiceConfig = new AuthServiceConfiguration
    .AuthConfigurationBuilder()
    .withRedirectUri("org.aerogear.mobile.example:/callback")
    .build();
----

. Before the auth service can be used `init` must be invoked once in an app
+
[source,java]
----
authService.init(context, authServiceConfig);
----
****

[role="secondary"]
.iOS
****
Set your custom configuration to the auth service instance, making sure the redirect URL matches the App's Bundle Id.

[source,swift]
----
// create the authentication config
let authenticationConfig = AuthenticationConfig(redirectURL: "org.aerogear.mobile.example:/callback")
try! AgsAuth.instance.configure(authConfig: authenticationConfig)
----
****

[role="secondary"]
.Cordova
****

Import and initialize Auth:

[source,javascript]
----
const Auth = require('@aerogear/auth').Auth;

const authService = new Auth();
const initOptions = { onLoad: "login-required" };

authService.init(initOptions)
    .then(() => {
        // successful init & authentication
    })
    .catch((err) => {
        // initialization error
    });
----

You can pass `login-required` or `check-sso` to the init function. `login-required` will authenticate the client if the user is logged in to Keycloak or display the login page if not. `check-sso` will only authenticate the client if the user is already logged in. If the user is not logged in the browser will be redirected back to the application and remain unauthenticated. By default, the `check-sso` option is used.

NOTE: Initialization will also perform authentication

****

[role="secondary"]
.Xamarin
****

. Create an link:https://developer.android.com/guide/topics/manifest/manifest-intro#ifs[intent filter] for the `net.openid.appauth.RedirectUriReceiverActivity` activity. This step is required for Xamarin Android and allows the login browser to redirect back to your App. Add this to your `AndroidManifest.xml`:
+
[source,xml]
----
<activity android:name="net.openid.appauth.RedirectUriReceiverActivity" android:exported="true"  android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="org.aerogear.mobile.example" />
    </intent-filter>
</activity>
----

. Initialize the Auth module
.. For an Android app (MainActivity.cs):
+
[source,csharp]
----
var app = new App();
MobileCoreAndroid.Init(app.GetType().Assembly,ApplicationContext);
var authService = AuthService.InitializeService();
var authConfig = AuthenticationConfig.Builder.RedirectUri("org.aerogear.mobile.example:/callback").Build();
authService.Configure(authConfig);
----
+
NOTE: For Android an link:https://developer.android.com/guide/topics/manifest/manifest-intro#ifs[Intent filter] should be configured with the callback URL specified in AuthenticateOptions in the App's AndroidManifest.xml. See the link:https://github.com/aerogear/xamarin-showcase-template/blob/master/Example.Android/Properties/AndroidManifest.xml[example app].

.. For an iOS app (AppDelegate.cs):
+
[source,swift]
----
var app = new App();
MobileCore core = MobileCoreIOS.Init(app.GetType().Assembly);
var authService = AuthService.InitializeService();
var authConfig = AuthenticationConfig.Builder.RedirectUri("org.aerogear.mobile.example:/callback").Build();
authService.Configure(authConfig);
----

****

== Next steps

xref:keycloak/authenticating.adoc[User authentication]
