//include::{partialsdir}/attributes.adoc[]

= Configuring the Service

The following section will guide you through configuring the schema of the redirect url and web origin for a client in {idm-name}. This is required to enable OpenID authentication.

:service-name: Identity Management

== Choose the schema of a redirect url

[role="primary"]
.Android
****
It is recommended to use the package name of the Android app followed by `:/callback` as the schema of the redirect url to avoid conflicts. (e.g. `com.aerogear.androidshowcase`)
****
[role="secondary"]
.iOS
****
It is recommended to use the Bundle Identifier of the iOS app followed by `:/callback` as the schema of the redirect url. (e.g. `org.aerogear.ios-showcase-template:/callback`)
****
[role="secondary"]
.Cordova
****
The schema of the redirect url should be `\http://localhost/*`.
****
[role="secondary"]
.Xamarin
****
Depending on the platform, set the redirect as described in either the Android or the iOS tab.
****

== Configuring {idm-name}

. Expand the {service-name} Service by clicking the *>* icon.

. Click on the Realm URL link to open the {idm-name} Administration Console.

. Log in to the Administration console using the credentials you specified at xref:keycloak/provisioning.adoc[Provisioning] (defaults to admin:admin)

. Open `Clients` from the menu.

. Open your client. The name of your client is derived from the name of the {mobile-client}, the name of the mobile development platform and the client type, for example `myapp-android-public`.

. Add `<schema>:/callback` to `Valid Redirect URIs`.

. Add `<schema>` to `Web Origins`.

. Save your changes.

NOTE: You must create a new user account before you can log into the Showcase App. To create a new user, follow the steps link:https://www.keycloak.org/docs/3.3/server_admin/topics/users/create-user.html[here] and to setup a new users credentials, follow the steps link:https://www.keycloak.org/docs/3.3/server_admin/topics/users/credentials.html[here].