//include::{partialsdir}/attributes.adoc[]

= Configuring the Identity Management Service

The following section will guide you through configuring the schema of the redirect url and web origin for a client in {idm-name}. This is required to enable OpenID authentication.

:service-name: Identity Management

include::{partialsdir}/generic-service-nav.adoc[]

. Click on the Realm URL link to open the {idm-name} Administration Console.

. Log in to the Administration console using the credentials you specified at xref:keycloak/provisioning.adoc[Provisioning] (defaults to admin:admin)

. Open `Clients` from the menu.

. Open your Android client.

. Add the schema to `Valid Redirect URIs`.

[role="primary"]
.Android
****
It is recommended to use the package name of the Android app followed by `:/callback` as the schema of the redirect url to avoid conflicts. (e.g. `com.aerogear.androidshowcase`)
****
[role="secondary"]
.iOS
****
It is recommended to use the Bundle Identifier of the iOS app followed by `:/callback` as the schema of the redirect url. (e.g. `org.aerogear.ios-showcase-template:/callback`)
****
[role="secondary"]
.Cordova
****
The schema of the redirect url should be `\http://localhost/*`.
****
[role="secondary"]
.Xamarin
****
Depending on the platform set the redirect as described in either the Android or the iOS tab.
****

. Add `*` to `Web Origins`.

. Save your changes.
