= Single Sign-On (SSO)

The Auth SDK uses OpenID Connect http://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth[Authorization Code Flow] to achieve SSO via a mobile device browser.

== Prerequisites

. A running AeroGear Auth service (Keycloak)
. Two apps on the same device that are both using the Auth SDK module

== Steps to achieve SSO via a device browser

For this guide, let's assume that your two apps are called **Email App** and **Messaging App**.

. Ensure the "Remember Me" option in Keycloak is turned on. In the admin UI click on *Realm Settings* section on the left hand side, and then click on *Login*. Turn on *Remember Me*.

. Now that your two iOS apps and Keycloak clients are setup, sign into the *Email App* with the user you have previously created. You should be redirected to your device browser which should have loaded the Keycloak login page.

. Next, enter in your credentials, make sure check the *Remember Me* option and login. You have now been authenticated on the *Email App* via the browser.

. Finally, try sign into the *Messaging App* and you should be automatically logged in as you have been previously authenticated in the *Email App* via the *_same_* browser.

== Known Issues

On iOS 11 and above, Apple has introduced https://developer.apple.com/documentation/safariservices/sfauthenticationsession[SFAuthenticationSession] for apps to perform SSO, instead of using the system Safari browser. However, there are a few known issues with this new feature and sometimes user may have to enter their credentials again in other apps, even if they have already logged in once previously in one of the apps.