= Security Services

== {device-security-service}

Device Trust page will check the mobile device for and give a security rating for the device based on the following checks

- Debugger Detected
- Root Access Detected
- Emulator Access Detected
- No Device Lock Enabled

To use Device Trust in the showcase app:

. Press the *Security* menu item.
. From the drop down press *Device Trust*.
. View the results of the Device security checks.
. Navigate to the {grafana-ui}, and view the metrics as described in xref:mobile-metrics.adoc[Analyzing App Usage].

== {app-security-service}

Application Trust will allow you to connect to the Mobile Security Service and that can be used to enable or disable an application from a remote console. 

NOTE: The service it will not disable the showcase application it will only demonstrate the functionality.

To use Application Trust in the showcase app:

. Press the *Security* menu item.
. From the drop down press *Application Trust*.
. Navigate to the Mobile Security Service link to set the enable/disable message as described in xref:app-security.adoc#monitoring[Using the App Security Console].
. Press the *CHECK THE SECURITY SERVICE* button to check the message from the service.