include::{partialsdir}/attributes.adoc[]

:service-name: Push Notifications

= Binding a {mobile-client} with the {service-name} service

== Prerequisites

[role="primary"]
.Android

****
* [x] A Google account
* [x] Access to the Firebase console. See link:google-setup.html[Firebase Setup] to get started.
****

[role="secondary"]
.iOS

****
* [x] An Apple Developer account
* [x] An APNs client TLS certificate. Have a look at link:apple-setup.html[APNs Setup] for further instructions.
****


include::{partialsdir}/generic-binding.adoc[]

When you bind a mobile client to the {unifiedpush-service} service, a variant is created to store the credentials required to communicate with a push network.
Those credentials need to be provided in the binding dialog.

First pick your *Mobile Client Type*. Depending on the selection you then have to fill out the fields for either Android or iOS.

[role="primary"]
.Android

****
You need to provide a *Server Key* and a *Sender ID*. Both can be found in the Firebase console under *Project Settings > Cloud Messaging*. Make sure that you have selected `Android` in the `Mobile Client Type` dropdown.
****

[role="secondary"]
.iOS

****
You need an APNs client TLS certificate. Have a look at link:apple-setup.html[APNs Setup] for instructions on how to obtain one. Make sure that you have selected `iOS` in the `Mobile Client Type` dropdown.
The certificate needs to be encoded in base64 before copying it into the field labelled `iOS .p12 file`. If you're on Mac OS run:

----
cat <path/to/your/.p12> | base64
----

If you're on Linux chances are that you're using a version of the base64 tool that does line wrapping. You need to disable this:

----
cat <path/to/your/.p12> | base64 --wrap=0
----

****

After clicking Bind your variant will be created in UPS and you should see a new binding for your mobile client.


