include::{partialsdir}/attributes.adoc[]

:service-name: Push Notifications

= Binding a {mobile-client} with the {service-name} service

== Prerequisites

[role="primary"]
.Android

****
* [x] Google account
* [x] Access to the Firebase console. Refer to link:https://firebase.google.com/docs/[Firebase Docs].
****

[role="secondary"]
.iOS

****
* [x] Apple Developer account
* [x] APNs client TLS certificate. Refer to link:https://help.apple.com/developer-account/#/dev82a71386a[official Apple guide].
****


include::{partialsdir}/generic-binding.adoc[]

=== Required Binding Parameters

Choose a *Mobile Client Type* and fill out the required fields:

[role="primary"]
.Android

****
- Enter a *Server Key* and a *Sender ID*. Both are present in the Firebase console.
- Ensure that you have selected `Android` in the `Mobile Client Type` dropdown menu.
****

[role="secondary"]
.iOS

****
- Ensure that you have selected `iOS` in the `Mobile Client Type` dropdown menu.
- Obtain an APNs client TLS certificate. Refer to link:https://help.apple.com/developer-account/#/dev82a71386a[official Apple guide]. 
- Encode the certificate using base64 and paste the encoded certificate into the field labeled `iOS .p12 file`. 
+
If you are using macOS, run:
+
----
cat <path/to/your/.p12> | base64
----
+
If you are using Linux, chances are that you are using a version of the base64 tool that does line wrapping.
Disable base64 line wrapping by using `--wrap=0` flag:
+
----
cat <path/to/your/.p12> | base64 --wrap=0
----

****
[start=6]
. Click *Bind*.
Unified Push server creates a new variant and the OpenShift console displays a new binding for your mobile client. A variant is used for the storage of the credentials provided in the Binding procedure.