include::{partialsdir}/attributes.adoc[]

:service-name: Push Notifications

= Binding a {mobile-client} with the {service-name} service

== Prerequisites

[role="primary"]
.Android

****
* [x] A Google account
* [x] Access to the Firebase console. Refer to link:https://firebase.google.com/docs/[Firebase Docs].
****

[role="secondary"]
.iOS

****
* [x] An Apple Developer account
* [x] An APNs client TLS certificate. Refer to link:https://help.apple.com/developer-account/#/dev82a71386a[official Apple guide].
****


include::{partialsdir}/generic-binding.adoc[]

When you bind a mobile client to the {unifiedpush-service} service, a variant is created to store the credentials required to communicate with a push network.
Those credentials need to be provided in the binding dialog.

Pick a *Mobile Client Type*. Fill out the required fields:

[role="primary"]
.Android

****
- Provide a *Server Key* and a *Sender ID*. Both can be found in the Firebase console
- Ensure that you have selected `Android` in the `Mobile Client Type` dropdown menu.
****

[role="secondary"]
.iOS

****
- Ensure that you have selected `iOS` in the `Mobile Client Type` dropdown menu.
- Acquire an APNs client TLS certificate. Refer to link:https://help.apple.com/developer-account/#/dev82a71386a[official Apple guide]. The certificate needs to be encoded in base64 before copying it into the field labeled `iOS .p12 file`. 
+
If you are using macOS, run:
+
----
cat <path/to/your/.p12> | base64
----
+
If you are using Linux, chances are that you are using a version of the base64 tool that does line wrapping. You need to disable this:
+
----
cat <path/to/your/.p12> | base64 --wrap=0
----

****

After clicking `Bind`, your variant will be created in UPS and you should see a new binding for your mobile client.


