include::{partialsdir}/attributes.adoc[]

:service-name: Push Notifications

= Binding a {mobile-client} with the {service-name} service

== Prerequisites

[role="primary"]
.Android

****
* [x] A Google account
* [x] Access to the Firebase console. Refer to link:https://firebase.google.com/docs/[Firebase Docs].
****

[role="secondary"]
.iOS

****
* [x] An Apple Developer account
* [x] An APNs client TLS certificate. Refer to link:https://help.apple.com/developer-account/#/dev82a71386a[official Apple guide].
****


include::{partialsdir}/generic-binding.adoc[]

- Provide the credentials When you bind a mobile client to the {unifiedpush-service} service, a variant is created to store the credentials required to communicate with a push network.
Provide these in the binding dialog.

+
Choose a *Mobile Client Type*. Fill out the required fields:
+
[role="primary"]
.Android

****
- Enter a *Server Key* and a *Sender ID*. Both are present in the Firebase console.
- Ensure that you have selected `Android` in the `Mobile Client Type` dropdown menu.
****

[role="secondary"]
.iOS

****
- Ensure that you have selected `iOS` in the `Mobile Client Type` dropdown menu.
- Obtain an APNs client TLS certificate. Refer to link:https://help.apple.com/developer-account/#/dev82a71386a[official Apple guide]. 
- Encode the certificate using base64 and copy the encoded certificate into the field labeled `iOS .p12 file`. 
+
If you are using macOS, run:
+
----
cat <path/to/your/.p12> | base64
----
+
If you are using Linux, chances are that you are using a version of the base64 tool that does line wrapping.
Disable base64 line wrapping by using `--wrap=0` flag:
+
----
cat <path/to/your/.p12> | base64 --wrap=0
----

****

. Click *Bind*.
UPS creates a new variant and the OpenShift console displays a new binding for your mobile client.

