include::{partialsdir}/attributes.adoc[]
:service-name: Push Notifications

= Binding a {mobile-client} with the {service-name} service

include::{partialsdir}/generic-binding.adoc[]

:service-name: Push Notifications
= Choosing the right binding parameters for the {service-name} service

When you bind a mobile client to {service-name} a variant is created to store the credentials required to communicate with a push network.
Those credentials need to be provided in the binding dialog. First pick your *Mobile Client Type*. Depending on the selection you then have to fill out the fields for either Android or iOS.

== Android Clients

Push for Android is realized by Firebase Cloud Messaging. Have a look at link:google-setup.html[Firebase Setup] to get started.
You need to provide a *Server Key* and a *Sender ID*. Both can be found in the Firebase console under *Project Settings / Cloud Messaging*.

== iOS Clients

You need a mobile provisioning certificate. Have a look at link:apple-setup.html[APNs Setup] for instructions on how to obtain one.