include::{partialsdir}/attributes.adoc[]

= Setting up {unifiedpush-service} service SDK

This guide will help you to set up the {unifiedpush-service} service SDK in your App.

== Prerequisites

[role="primary"]
.Android

****
You need a Firebase account. See link:google-setup.html[Google setup] to get started.
****

[role="secondary"]
.iOS

****
You need to set up APNs. See link:proc_preparing-ups-for-use-with-ios.adoc[Apple setup] to get started.
****

== Importing the libraries

[role="primary"]
.Android

****

. Add the push dependency to your application module
+
[source,groovy]
----
implementation "org.aerogear:aerogear-push:[version]"
implementation "com.google.firebase:firebase-messaging:[version]"
----
+
.Firebase setup
+
In order to receive push messages you need to setup the Firebase in your project.
+
. Create a new project in link:https://console.firebase.google.com[Firebase console]
. Add link:https://developers.google.com/android/guides/google-services-plugin[The Google Services Gradle Plugin] in your root `build.gradle` file
[source,groovy]
  buildscript {
      dependencies {
          classpath 'com.google.gms:google-services:[version]'
      }
  }
. Apply the plugin in your app `build.gradle` file
[source,groovy]
  // ADD THIS AT THE BOTTOM
  apply plugin: 'com.google.gms.google-services'
. Download `google-services.json` an drop it in your app folder. For more details see link:google-setup.html[Google setup].

****

[role="secondary"]
.iOS

****
To import the SDK just use:
----
import AGSAuth
----
****

[role="secondary"]
.Cordova

****

Just install `cordova-plugin-aerogear-push`, it already includes the platform push plugin:

[source,bash]
----
$ cordova plugin add @aerogear/cordova-plugin-aerogear-push
----

Ionic Apps require an additional dependency, the link:https://ionicframework.com/docs/native/push/[Ionic Native Push Library]

[source,bash]
----
npm install --save @ionic-native/push
----

Finally you need to install a small wrapper library needed for registration:

[source,bash]
----
npm install --save @aerogear/push
----

****



== Device registration

To make use of the {unifiedpush-service} service devices need to be registered by calling an endpoint of the server.
The SDKs will handle this for you and the following steps will give you everything you need to start working with push notifications.

[role="primary"]
.Android

****

. Getting an instance of the PushService
+
[source,java]
----
PushService pushService = new PushService.Builder().openshift().build();
----

. Registration request
+
[source,java]
----
pushService.registerDevice()
  .requestOn(new AppExecutors().mainThread())
  .respondWith(new Responder<Boolean>() {
    @Override
    public void onResult(Boolean value) { // Yay }

    @Override
    public void onException(Exception exception) { // Oops! }
});
----

****

[role="secondary"]
.iOS

****

[source,swift]
----
func application(_ application: UIApplication,
                 didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    var config = UnifiedPushConfig()
    AgsPush.instance.register(
        deviceToken,
        config,
        success: {
           print("Successfully registered to Unified Push Server")
        },
        failure: { (error: Error!) in
           print("Failure to register for on Unified Push Server: \(error)")
        }
    )
}
----

****

[role="secondary"]
.Cordova

****

[source,javascript]
----
// Registration handler
pushObject.on('registration').subscribe(data => {
  // PushRegistration will handle the device registration with the Unifiedpush Server
  new PushRegistration().register(data.registrationId).then(() => {
    // Registration with UPS successful, you can now send push notifications from the UPS UI
  }).catch(err => {
    // Error on device registration
  });
});
----


