include::{partialsdir}/attributes.adoc[]

//':context:' is a vital parameter. See: http://asciidoctor.org/docs/user-manual/#include-multiple
:context: con_introduction-to-push-notification

[id='{context}_con_introduction-to-push-notification']
= About {unifiedpush-service} Service

[[overview]]
== Overview


include::{partialsdir}/generic-service-intros.adoc[tags=pushnotification-service]


Currently the service supports:


* link:https://developer.apple.com/notifications/[Apple Push Notification Service]
* link:https://firebase.google.com/products/cloud-messaging/[Firebase Cloud Messaging]

include::./ref_terminology.adoc[leveloffset=+1]

== Privacy note

As explained in the _link:#_how_the_unifiedpush_server_works[How the UnifiedPush Server works]_ section, the payload of the push notification is delivered to 3rd party Push Network providers, like Google or Apple.

WARNING: It is highly recommended to not sent any send sensitive personal or confidential information belonging to an individual (e.g. a social security number, financial account or transactional information, or any information where the individual may have a reasonable expectation of secure transmission) as part of any Push Notification!

For analytic purposes on our link:#_dashboard[Dashboard] we store the content of the +alert+ key sent to the UnifiedPush Server. The content of the +alert+ key belongs to the metadata, which is deleted after 30 days, using a nightly job within the UnifiedPush Server.


== How the UnifiedPush Server Works

The {unifiedpush-service} service offers a unified Notification Service API to the above mentioned Push Network Services.
It can be seen as a _broker_ that distributes push messages to different 3rd party Push Networks.


NOTE: When using the UnifiedPush Server, please keep in mind that Push notification is a signalling mechanism and that it is not suitable to be used as a data carrying system (e.g. use in a chat application).

== Prerequisites

include::{partialsdir}/generic-provisioning-pre-req.adoc[]