include::{partialsdir}/attributes.adoc[]

= Sending Push Notifications

The {push-ui} allows you to send {push-notification}s to devices.

== Prerequisites

- Access to the {push-ui}.
- An application with at least 1 binding or variant.

== Procedure

Once in the {push-ui}:

. Select the target application from the home page and click on *Send Notification To This App*.

. In the displayed dialog, enter some text in the *Message* form. 

. Click on *Send Push Notification* button.

Your message is now delivered by the 3rd party Push Network to your device.

TIP: You can give a higher priority to a push message by changing *Priority* to 'high' instead of 'normal'.

== Filtering recipients

It is possible to select a more specific set of recipients by adding additional values to *Variants*, *Alias*, *Device Types* and *Category*.

In order to filter it, a {mobile-client} has to be associated with at least 1 or more of these parameters. This is done while xref:ROOT:push/coding.adoc[Registering a Device].
