// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// Base the file name and the ID on the module title. For example:
// * file name: doing-procedure-a.adoc
// * ID: [id='doing-procedure-a']
// * Title: = Doing procedure A

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
:context: {keycloak-service}
[id='implementing-authentication-{context}']
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= Implementing authentication

.Prerequisites

* xref:getting-started-with-user-authentication-{context}[Getting Started with User Authentication].

.Procedure

. Implement authentication using the Aerogear SDK on all the supported platforms.

[role="primary"]
.Android
****

. Provide an implementation of `Callback` which is defined in the Aerogear SDK and used to handle asynchronous results:
+
[source,java]
----
Callback authCallback = new Callback<UserPrincipal>() {
    @Override
    public void onSuccess(UserPrincipal principal) {
        ...
    }

    @Override
    public void onError(Throwable error) {
        ...
    }
};
----

. Use the `login` method to hand over to the login browser:
+
[source,java]
----
// Build the options object and start the authentication flow
DefaultAuthenticateOptions options = new DefaultAuthenticateOptions(myActivity, LOGIN_RESULT_CODE);

authService.login(options, authCallback);
----

. Override `onActivityResult` to handle the result from the browser. It's important to pass the intent back to the Auth service:
+
[source,java]
----
@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {
    if (requestCode == LOGIN_RESULT_CODE) {
        authService.handleAuthResult(data);
    }
}
----
+
NOTE: This handler should always invoke `handleAuthResult`, providing the `Intent`. This will exchange the temporary tokens returned from `login` for long-lived tokens and will provide a `UserPrincipal` which can be used to access a users details. If this is not invoked you will not have access to the `UserPrincipal`.

. The callback provided to `login` will be invoked.
****

[role="secondary"]
.iOS
****
. Use the `login` method to hand over to the login browser:
+
[source,swift]
----
AgsAuth.instance.login(presentingViewController: self, onCompleted: onLoginComplete)

func onLoginComplete(user: User?, err: Error?) {
    if let error = err {
        return
    }

    let currentUser = user
}
----

. Allow your application to handle the redirect in `AppDelegate`:
+
[source,swift]
----
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey: Any] = [:]) -> Bool {
    do {
        return try AgsAuth.instance.resumeAuth(url: url as URL)
    } catch AgsAuth.Errors.serviceNotConfigured {
        print("AeroGear auth service is not configured")
    } catch {
        fatalError("Unexpected error: \(error).")
    }
    return false
}
----
****

[role="secondary"]
.Cordova
****
Authentication will be performed on initialization as described in the section xref:identity-management.adoc#initializing-the-sdk[Initializing the SDK]. To manually redirect to the login screen, use:
[source,javascript]
----
authService.login().then(() => {
    // Login success
}).catch(() => {
    // Login error
});;
----
****

[role="secondary"]
.Xamarin
****
. Use the `Authenticate` method to hand over to the login browser:
+
[source,csharp]
----
IAuthService authService = MobileCore.Instance.GetService<IAuthService>();

var authOptions = DependencyService.Get<IAuthenticateOptionsProvider>().GetOptions();
var user = await authService.Authenticate(authOptions);
----
****

.Additional resources

* A bulleted list of links to other material closely related to the contents of the concept module.
