:context: {keycloak-service}
[id='refreshing-the-authentication-token-{context}']
= Refreshing the authentication token

When a user is authenticated, an access token and a refresh token are generated by the authentication server.
See the link:https://www.keycloak.org/docs/3.2/server_admin/topics/sessions/timeouts.html[Keycloak documentation] for information about configuring the lifespan of these tokens.
If the refresh token is still valid, the authentication token can be refreshed even if the authentication token has expired.

.Prerequisites

* A working mobile app that uses authentication with the {keycloak-service} service.

.Procedure

To automatically refresh the authenticate token :

[role="primary"]
.Android
****

Retrieve the current user and refresh the access token when possible and required:

[source,java]
----
UserPrincipal currentUser = authService.currentUser(true);
----
****

[role="secondary"]
.iOS
****
Retrieve the current user and refresh the access token when possible and required:

[source,swift]
----
do {
    try AgsAuth.instance.currentUser(autoRefresh: true) { (currentUser, error) in
        // If error is nil, currentUser is now refreshed
    }
} catch {
    // An error has occurred trying to reach the authentication server
}
----
****

[role="secondary"]
.Cordova
****
Retrieve the keycloak adapter object and refresh the access token, when possible and required:

[source,javascript]
----
authService.service.extract().updateToken(30).then(() => {
    // Token has been refreshed
});
----

More information about the keycloak javascript adapter can be found link:https://www.keycloak.org/docs/3.0/securing_apps/topics/oidc/javascript-adapter.html[here]
****

[role="secondary"]
.Xamarin
****
Retrieve the current user and refresh, if needed and still possible, its access token:

[source,csharp]
----
var authService = MobileCore.Instance.GetService<IAuthService>();
var currentUser = await authService.CurrentUser(true);
----
****

