// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// Base the file name and the ID on the module title. For example:
// * file name: doing-procedure-a.adoc
// * ID: [id='doing-procedure-a']
// * Title: = Doing procedure A

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
:context: {keycloak-service}
[id='configuring-{context}']
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.
= Configuring the {keycloak-service} Service

This section guides you through configuring the schema of the redirect url and web origin for a client in {idm-name}.
This is required to enable OpenID authentication.
For an explanation of these terms, see link:https://www.keycloak.org/documentation.html[Keycloak Documentation].

.Prerequisites

* xref:a-collection-of-modules[Working with the {keycloak-service} Service].

.Procedure

. Choose the schema of a redirect url
+
[role="primary"]
.Android
****
It is recommended to use the package name of the Android app as the schema of the redirect url to avoid conflicts. (e.g. `com.aerogear.androidshowcase`)
****
+
[role="secondary"]
.iOS
+
****
It is recommended to use the Bundle Identifier of the iOS app as the schema of the redirect url. (e.g. `org.aerogear.ios-showcase-template`)
****
+
[role="secondary"]
.Cordova
+
****
Redirect url is `\http://localhost/\*`, without `:/callback`. Web Origin is `\http://localhost/*`.
****
+
[role="secondary"]
.Xamarin
+
****
Depending on the platform, set the redirect as described in either the Android or the iOS tab.
****
+
. Log into the OpenShift console and navigate to the Project Overview.

. Navigate to the {mobile-client} screen.

. Select the Mobile Services tab.

. If a binding to the {keycloak-service} service is in progress, a spinning icon is displayed to the right of the {keycloak-service} entry. Wait for the binding process to complete.

. If the _Keycloak Realm URL_ URL is not visible, expand the Identity Management Service by clicking the > icon.

. Click on the *Keycloak Realm URL* link to open the Keycloak Administration Console.

. Log in to the Administration console using the credentials you specified when xref:#provisioning[Provisioning] the service (defaults to admin:admin).

. Select `Clients` from the left navigation menu.

. Select your client from the list of clients. The name of your client is derived from the name of the {mobile-client}, the name of the mobile development platform and the client type, for example `myapp-android-public`.

. Add `<schema>:/callback` as an additional entry to `Valid Redirect URIs`. See xref:choose-schema[] to determine the value for `<schema>`.

. Add `<schema>` as an additional entry to `Web Origins`.  See xref:choose-schema[] to determine the value for `<schema>`.

. Save your changes.

. Create a new user account as described in link:https://www.keycloak.org/docs/3.3/server_admin/topics/users/create-user.html[Creating a New User].

. Set up credentials for the new user as described in link:https://www.keycloak.org/docs/3.3/server_admin/topics/users/credentials.html[User Credentials].

.Additional resources

* A bulleted list of links to other material closely related to the contents of the concept module.
