// For more information, see: https://redhat-documentation.github.io/modular-docs/

[id='authenticating-with-a-back-end-service-{context}']
= Authenticating with a back end service

In a typical scenario, you not only want the user to authenticate on the mobile app, you also want that user to authenticate with a back end service.

.Prerequisites

*  A working mobile app that uses authentication with the {keycloak-service} service.

.Procedure

. Add an additional token:
+
[source]
----
Authorization: BEARER Yourtoken
----

. Add code to authenticate with a back end service:
+
[tabs]
====
// tag::excludeDownstream[]
Android::
+
--

. Retrieve the current user:
+
[source,java]
----
UserPrincipal currentUser = authService.currentUser();
----

. Implement `Callback` and call `logout`:
[source,java]
----
authService.logout(currentUser, new Callback<UserPrincipal>() {
    @Override
    public void onSuccess() {
        // User Logged Out Successfully and local Auth tokens were Deleted
    }

    @Override
    public void onError(Throwable error) {
        // An error occurred during logout
    }
});
----
--
iOS::
+
--
. Implement the logout callback:
+
[source,swift]
----
func onLogoutComplete(_: Error?) {
    // User Logged Out Successfully and local Auth tokens were Deleted
    ...
}
----

. Call `logout` and pass the callback:
+
[source,swift]
----
do {
    try AgsAuth.instance.logout(onCompleted: self.onLogoutComplete)
} catch {
    fatalError("Error logging out: \(error).")
}
----
--
// end::excludeDownstream[]
Cordova::
+
--
To logout invoke the `logout` function:

[source,javascript]
----
authService.logout().then(() => {
    // User Logged Out Successfully and local Auth tokens were Deleted
});
----
--
// tag::excludeDownstream[]
Xamarin::
+
--
To logout invoke the `Logout` method:
[source,csharp]
----
var authService = MobileCore.Instance.GetService<IAuthService>();
var result = await authService.Logout(authService.CurrentUser());
----
--
// end::excludeDownstream[]
====

.Additional resources

// tag::excludeDownstream[]

* xref:android-additional-configuration[Additional configuration for Android]

// end::excludeDownstream[]

* link:https://www.keycloak.org/docs/3.3/server_admin/topics/identity-broker/oidc.html[Keycloak OICD Providers^]
