// For more information, see: https://redhat-documentation.github.io/modular-docs/

[id='configuring-{context}']
= Configuring the {keycloak-service} Service

This section guides you through configuring the redirect url and web origin for a client in {idm-name}.
This is required to enable OpenID authentication.
For an explanation of these terms, see link:{sso-docs-link}[{sso-name} Documentation].

.Prerequisites

* An understanding of link:https://openid.net/[OpenID^]

.Procedure

. Log into the {mobile-developer-console} and navigate to the {mobile-client} screen.

. Select the *Mobile Services* tab.

. If a binding to the {keycloak-service} service is in progress, a spinning icon is displayed to the right of the {keycloak-service} entry. Wait for the binding process to complete.

. If the _Keycloak Realm URL_ URL is not visible, expand the Identity Management Service by clicking the > icon.

. Click on the *Keycloak Realm URL* link to open the Keycloak Administration Console.
+
// TODO: @wei will default credentials always be as follows?
. Log in to the Administration console using the credentials you specified when xref:#provisioning[Provisioning] the service (defaults to admin/admin).

. Select `Clients` from the left navigation menu.
+
// TODO: with a cordova app, I didn't see mobile development platform
. Select your client from the list of clients. The name of your client is derived from the name of the {mobile-client}, the name of the mobile development platform and the client type, for example `myapp-android-public`.


. Add an additional entry to *Valid Redirect URIs* as follows:
+
[tabs]
====
// tag::excludeDownstream[]
Android::
+
--
It is recommended to use the package name of the Android app as the schema of the redirect url to avoid conflicts. (e.g. `com.aerogear.androidshowcase`)
--
iOS::
+
--
It is recommended to use the Bundle Identifier of the iOS app as the schema of the redirect url. (e.g. `org.aerogear.ios-showcase-template`)
--
// end::excludeDownstream[]
Cordova::
+
--
Set the additional value to `\http://localhost/\*`. 
--
// tag::excludeDownstream[]
Xamarin::
+
--
Depending on the platform, set the redirect URL as described in either the Android or the iOS tab.
--
// end::excludeDownstream[]
====

. Add an additional entry to *Web Origins* as follows:
+
[tabs]
====
// tag::excludeDownstream[]
Android::
+
--
Use the package name of the Android app to avoid conflicts. (e.g. `com.aerogear.androidshowcase`)
--
iOS::
+
--
Use the Bundle Identifier of the iOS app. (e.g. `org.aerogear.ios-showcase-template`)
--
// end::excludeDownstream[]
Cordova::
+
--
Set additional value to `\http://localhost/\*`. 
--
// tag::excludeDownstream[]
Xamarin::
+
--
Depending on the target platform, set the additional value as described in either the Android or the iOS tab.
--
// end::excludeDownstream[]
====


. Save your changes.

. Create a new user account as described in link:https://www.keycloak.org/docs/3.3/server_admin/topics/users/create-user.html[Creating a New User].

. Set up credentials for the new user as described in link:https://www.keycloak.org/docs/3.3/server_admin/topics/users/credentials.html[User Credentials].
