// For more information, see: https://redhat-documentation.github.io/modular-docs/

[id='setting-up-sdk-{context}']
= Setting up the {keycloak-service} Service SDK

This section helps you to set up the {keycloak-service} service SDK in your App.
It describes how to set up and initialize the {keycloak-service} service SDK.

.Prerequisites

* Your local `mobile-services.json` file is up-to-date.

.Procedure

. Import the libraries.
+
[tabs]
====
// tag::excludeDownstream[]
Android::
+
--
. Add the following dependency in your app's *build.gradle*:
+
[source,groovy,subs="attributes"]
----
dependencies {
    implementation "org.aerogear:android-auth:{release-number}"
}
----
. To prevent build errors, add the following in your app's *build.gradle*:
[source,groovy,subs="attributes"]
+
----
compileOptions {
    sourceCompatibility 1.8
    targetCompatibility 1.8
}
----
--
iOS::
+
--
. Add the dependency to your *Podfile*:
+
[source,ruby,subs="attributes"]
----
target '[TARGET NAME]' do
    pod 'AGSAuth', '{release-number}'
end
----

. Update the dependencies:
+
[source,bash]
----
$ pod install
----

. Import and instantiate `AGSAuth` to start using the SDK:
+
[source,swift]
----
import AGSAuth

auth = AGSAuth()
----
--
Cordova::
+
--
// end::excludeDownstream[]
. Add the following code to `index.html` located in `src/` :
+
[source,html]
----
<meta http-equiv="Content-Security-Policy" content="default-src * file: 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">
----
. Install the link:https://www.npmjs.com/package/@aerogear/auth[AeroGear Auth] package from link:https://www.npmjs.com/[NPM^] in `src/`:
+
[source,bash]
----
$ npm install @aerogear/auth
----
. In order for a node module to work in a browser (and on Cordova), use `browserify` to allow for the use of a `require` statement.

// tag::excludeDownstream[]
--
Xamarin::
+
--
. Install link:https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools[NuGet^].

. Install the link:https://www.nuget.org/packages/AeroGear.Mobile.Core[AeroGear Core^] package:
+
[source,bash,subs="attributes"]
----
dotnet add package AeroGear.Mobile.Core --version {release-number}
----

. For Android run:
+
[source,bash,subs="attributes"]
----
dotnet add package AeroGear.Mobile.Core.Platform.Android --version {release-number}
dotnet add package AeroGear.Mobile.Auth.Platform.Android --version {release-number}
----

. For iOS run:
+
[source,bash,subs="attributes"]
----
dotnet add package AeroGear.Mobile.Core.Platform.iOS --version {release-number}
dotnet add package AeroGear.Mobile.Auth.Platform.iOS --version {release-number}
----
--
// end::excludeDownstream[]
====

. Initialize the SDK.
+
[tabs]
====
// tag::excludeDownstream[]
Android::
+
--

. Specify the redirect URL. It is recommended to use the package name of your app.
+
----
AuthServiceConfiguration authServiceConfig = new AuthServiceConfiguration
    .AuthConfigurationBuilder()
    .withRedirectUri("org.aerogear.mobile.example:/callback")
    .build();
----

. Create the auth service:
+
[source,java]
----
AuthService authService = new AuthService(authServiceConfig);
----
--
iOS::
+
--
Set your custom configuration to the auth service instance, making sure the redirect URL matches the App's Bundle Id.

[source,swift]
----
// create the authentication config
let authenticationConfig = AuthenticationConfig(redirectURL: "org.aerogear.mobile.example:/callback")
try! AgsAuth.instance.configure(authConfig: authenticationConfig, useExternalUserAgent: false)
----
--
Cordova::
+
--
// end::excludeDownstream[]

. Import and initialize Auth.
. Replace `import` with `require` in the `init` section, as displayed in the following snippet:
+
[source,javascript]
----
const Auth = require('@aerogear/auth').Auth;

const authService = new Auth(app.config);
const initOptions = { onLoad: "login-required" };

authService.init(initOptions)
    .then(() => {
        // successful init & authentication
    })
    .catch((err) => {
        // initialization error
    });
----

You can pass `login-required` or `check-sso` to the init function. `login-required` will authenticate the client if the user is logged in to Keycloak or display the login page if not. `check-sso` will only authenticate the client if the user is already logged in. If the user is not logged in the browser will be redirected back to the application and remain unauthenticated. By default, the `check-sso` option is used.

NOTE: Initialization also enables authentication.

.To use self-signed certificates with Cordova Android:
. Create a file `network_security_config.xml` in your project with the following code:
+
[source,xml]
----
<network-security-config>
  <base-config>
    <trust-anchors>
      <certificates src="user"/>
      <certificates src="system"/>
    </trust-anchors>
  </base-config>
</network-security-config>
----
. Include it into the `config.xml` file for the `android` platform
+
[source,xml]
----
<resource-file src="network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
    <application android:networkSecurityConfig="@xml/network_security_config" />
</edit-config>
----
. Add `xmlns:android="http://schemas.android.com/apk/res/android"` to the `widget` tag in the `config.xml` file

// tag::excludeDownstream[]
--
Xamarin::
+
--
. Create an link:https://developer.android.com/guide/topics/manifest/manifest-intro#ifs[intent filter^] for the `net.openid.appauth.RedirectUriReceiverActivity` activity. This step is required for Xamarin Android and allows the login browser to redirect back to your App. Add this to your `AndroidManifest.xml`:
+
[source,xml]
----
<activity android:name="net.openid.appauth.RedirectUriReceiverActivity" android:exported="true"  android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="org.aerogear.mobile.example" />
    </intent-filter>
</activity>
----

. Initialize the Auth module
.. For an Android app (MainActivity.cs):
+
[source,csharp]
----
var app = new App();
MobileCoreAndroid.Init(app.GetType().Assembly,ApplicationContext);
var authService = AuthService.InitializeService();
var authConfig = AuthenticationConfig.Builder.RedirectUri("org.aerogear.mobile.example:/callback").Build();
authService.Configure(authConfig);
----
+
NOTE: For Android an link:https://developer.android.com/guide/topics/manifest/manifest-intro#ifs[Intent filter^] should be configured with the callback URL specified in AuthenticateOptions in the App's AndroidManifest.xml. See the link:https://github.com/aerogear/xamarin-showcase-template/blob/master/Example.Android/Properties/AndroidManifest.xml[example app^].

.. For an iOS app (FinishedLaunching method of AppDelegate.cs):
+
[source,swift]
----
var app = new App();
MobileCore core = MobileCoreIOS.Init(app.GetType().Assembly);
var authService = AuthService.InitializeService();
var authConfig = AuthenticationConfig.Builder.RedirectUri("org.aerogear.mobile.example:/callback").Build();
authService.Configure(authConfig);
----

. To use self-signed certificates with Xamarin Android:
.. Create a file at `Resources/xml/network_security_config.xml` with the following code:
+
[source,xml]
----
<network-security-config>
  <base-config>
    <trust-anchors>
      <certificates src="user"/>
      <certificates src="system"/>
    </trust-anchors>
  </base-config>
</network-security-config>
----
.. Add the following value to the `<application>` tag in `AndroidManifest.xml`:
+
[source,xml]
----
android:networkSecurityConfig="@xml/network_security_config"
----
--
// end::excludeDownstream[]
====
