include::{partialsdir}/attributes.adoc[]

//':context:' is a vital parameter. See: http://asciidoctor.org/docs/user-manual/#include-multiple
:context: data_sources_ui

[id='{context}_data_sources_ui']
= Managing your data sources using the {sync-service} UI

The {sync-service} UI allows you to manage your data sources.

To access the {sync-service} UI, you will need to:

 * Make sure it is xref:sync/provisioning.adoc[provisioned].
 * Select a route in OpenShift.
 * Login with your OpenShift credentials.

NOTE: On first login you need to provide the OpenShift OAuth service permissions to read your user account.

== Data Source Introduction

A Data Source is a representation of your data storage solution. The Data Source consists of a *Name*, a *Type*, and a *Configuration*. 
The *Type* of Data Source which are currently supported are *Postgres* and *InMemory*. For information on how to use *Postgres*, refer to the documentation https://www.postgresql.org/docs[here]. 
The *In Memory* Data Source that is currently supported is *NeDB*, for more information on how to use this please refer to the the documentation https://github.com/louischatriot/nedb[here]. 

NOTE: The *In Memory* Data Source is not recommended for production use.

== Data Source Options

The data sources tab on the {sync-service} UI allows you to perform the following operatations:

=== View Existing Data Sources

This is the default view on the {sync-service} UI. It lists all of the existing data sources. This view currently displays the data source name and the type of the data source. 

Data sources can be filtered using the *name* property.

=== Edit an Existing Data Source

To edit an existing data source, choose the *Edit Data Source* option from the data source menu.

Update the data source with the new values.

=== Delete an Existing Data Source

To delete a data source, choose the *Delete Data Source* option from the data source menu. Next confirm that you wish to delete the data source.

NOTE: When you delete a data source, all resolvers that are attached to it will also be deleted.

=== Create a New Data Source

If no data source exists, a new data source can be created by clicking the *Add Data Source* button. Select the type of your data source from the dropdown.
For more information about the _In Memory_ option have a look at xref:#in-memory-option[the In Memory Option]. Information about the Postgres option can be found xref:#in-memory-option[here].

[[in-memory-option]]
=== In Memory Data Sources

You need to provide a name for the data source. The only other option is `TimeStamp Data`. If checked, timestamps will be stored along with your data in `NeDB`.

[[postgres-option]]
=== Postgres Data Sources

You need to provide a name for the data source. `Postgres` has a number of other required options:

. _Server_: The URL where the PostgreSQL server is located.
. _Port_: The Network Port used by PostgreSQL (defaults to `5432`).
. _Database_: The name of the database to connect to. PostgreSQL servers can host multiple databases.
. _Username_: The username of the PostgreSQL user account.
. _Password_: (Optional) The password of the PostgreSQL user account.

NOTE: You can test your data source before saving by clicking on the `Test` button. Data Sync will then attempt to connect to the provided PostgreSQL server. If the connection fails you will see the error message in the dialog.