include::{partialsdir}/attributes.adoc[]

//':context:' is a vital parameter. See: http://asciidoctor.org/docs/user-manual/#include-multiple
:context: data_sources_ui

[id='{context}_data_sources_ui']
= Managing your data sources using the {sync-service} UI

The {sync-service} UI allows you to manage your data sources.

To access the {sync-service} UI, you will need to:

 * Make sure it is xref:sync/provisioning.adoc[provisioned].
 * Select a route in OpenShift.
 * Login with your OpenShift credentials.

NOTE: On first login you need to provide the OpenShift OAuth service permissions to read your user account.

== Data Source Introduction

A Data Source is a representation of your data storage solution. The Data Source consists of a *Name*, a *Type*, and a *Configuration*. 
The *Type* of Data Source which are currently supported are *Postgres* and *InMemory*. For information on how to use *Postgres*, refer to the documentation https://www.postgresql.org/docs[here]. 
The *In Memory* Data Source that is currently supported is *NeDB*, for more information on how to use this please refer to the the documentation https://github.com/louischatriot/nedb[here]. 

NOTE: The *In Memory* Data Source is not recommended for production use.

== Data Source Options

The data sources tab on the {sync-service} UI allows you to perform the following operatations:

=== View Existing Data Sources

This is the default view on the {sync-service} UI. It lists all of the existing data sources. This view currently displays the data source name and the type of the data source. 

Data sources can be filtered using the *name* property.

=== Edit an Existing Data Source

To edit an existing data source, choose the *Edit Data Source* option from the data source menu.

Update the data source with the new values.

=== Delete an Existing Data Source

To delete a data source, choose the *Delete Data Source* option from the data source menu. Next confirm that you wish to delete the data source.

NOTE: When you delete a data source, all resolvers that are attached to it will also be deleted.

=== Create a New Data Source

If no data source exists, a new data source can be created by clicking the *Add Data Source* button

Enter the *name* of the data source into the required fields on the modal. Next choose if you would like to add timestamps to your records.
