

[[building-and-deploying-the-showcase-apps]]
[#build]
== Building and Running the Showcase App

. Build the Mobile App

[tabs]
====
Ionic::
+
--
[source,bash,subs="attributes"]
----
$ npm install
$ npm run ionic:build
----
--
// tag::excludeAll[]
Android::
+
--
[source,bash,subs="attributes"]
----
$ ./gradlew assembleDebug
----
--
iOS::
+
--
Run this command to install dependencies:

. Install CocoaPods as described in link:https://cocoapods.org/[] if it is not already installed.

. Run this command to install dependencies:
+
[source,bash]
----
$ pod install
----
--
Xamarin::
+
--
Run this command to install dependencies (optional):

[source,bash]
----
$ nuget restore
----
--
// end::excludeAll[]
====

[start=2]
. Run the Mobile App

[tabs]
====
Ionic::
+
--
To run the showcase app, use these commands:

[source,bash,subs="attributes"]
----
$ npm run ionic:android # to run on an Android device or emulator
$ npm run ionic:ios # to run on an iOS device or emulator
----

These commands would run the app on a device if connected or on the emulator if no device is connected.

Alternatively, you can use Cordova commands directly to specify the target:

[source,bash,subs="attributes"]
----
$ ionic cordova run android --device      # run on a connected device
$ ionic cordova run android --emulator    # run on the Android emulator
----
--
// tag::excludeAll[]
Android::
+
--
Following command installs and runs the debug version of the showcase app on the connected device if any. If there is
no connected device, it installs and runs the application on the emulator.

[source,bash,subs="attributes"]
----
$ ./gradlew installDebug
----
--
iOS::
+
--
Open up `.xcworkspace` with Xcode  and click the *Build & Run* button in Xcode. This should start the showcase application in an emulator.

NOTE: Do not use `.xcodeproj`. If you open up a project file instead of a workspace, dependencies will not be correctly configured.

--
Xamarin::
+
--
1. Open up `xamarin-showcase-template.sln` with VisualStudio.
2. If you didn't run `nuget restore` before, right click on the solution in the left pane then click on `Restore Nuget Packages`.
3. In the top bar, select the project to run: `Example.Android` or `Example.iOS`
4. Again in the top bar, select the correct configuration:
    * Debug/Release: for compiling Example.Android
    * [Debug|Release]|iPhoneSimulator: to compile and run Example.iOS on the iPhoneSimulator
    * [Debug|Release]|iPhone: to compile and run Example.iOS on a real iPhone device
5. At the right of the configuration, select the target device (the android or iPhone version)
6. Click on *Build -> Rebuild All*
7. Click on the *Run* button in the top left

NOTE: If no android devices are selectable, it could mean that no virtual android devices has been configured. To add one, click on *Tools->Device Manager->Add Device*
--
// end::excludeAll[]
====
