. Navigate to your project in OpenShift.
. On the *Overview* screen, expand your {mobile-client} to view the *CLIENT INFO*.
. Copy the configuration to your clipboard and paste it to the `mobile-services.json` file in the showcase app depending on the platform:

[tabs]
====
// tag::excludeDownstream[]
Android::
+
--

Update this file at the following location in your Android showcase project:

`android-showcase-template/app/src/main/assets/mobile-services.json`

--
iOS::
+
--

Update this file at the following location in your iOS showcase project:

`ios-showcase-template/ios-showcase-template/mobile-services.json`

--
// end::excludeDownstream[]
Cordova::
+
--

Update this file at the following location in your Cordova showcase project

`cordova-showcase-template/src/mobile-services.json`

--
// tag::excludeDownstream[]
Xamarin::
+
--

Update this file at the following location in your Xamarin showcase project:

`xamarin-showcase-template/Example/Resources/mobile-services.json`

--
// end::excludeDownstream[]
====
