


// maybe change attr to {pushnotification-service}

= {unifiedpush-service} Service
//tag::pushnotification-service[]

The {unifiedpush-service} service allows you to send native push notifications to different mobile operating systems.

* Code once and push notifications to iOS and Android
* Push notifications to defined groups
* Push notifications to either iOS only or Android only
* Push notifications to different variants of a mobile app
* Push notifications from different back-end apps to the same mobile app

//end::pushnotification-service[]



= {metrics-service} Service
//tag::metrics-service[]

The {metrics-service} service allows you to gather metrics on mobile apps, device versions, device security checks and back-end mobile service usage.

* Monitor usage by version of mobile app, platform and SDK
* Monitor interactions with the Identity Management service

//end::metrics-service[]


// change to {identitymanagement-service} maybe 

= {keycloak-service}
//tag::identitymanagement-service[]

The {keycloak-service} service allows you to add authentication and authorization to your mobile app.

* Secure your mobile app using the industry standard OpenID Connect protocol
* Add access control to your app based on user’s group membership
* Easily implement SSO, multi-factor authentication and Social Login support
* Back-end support for identity brokering and user federation

//end::identitymanagement-service[]


//change to {mobilecicd-service} maybe 

= {mobile-ci-cd-service}
//tag::mobilecicd-service[]

The {mobile-ci-cd-service} service allows you to automate the building of your native and hybrid mobile app for both Android and iOS.

* Leverage your Jenkins expertise to manage and automate mobile builds.
* Containerised builds on OpenShift for Android
* Support for integrating OSX as build slaves for iOS builds
* Catch build errors early using automated builds
* Build status is displayed on the {mobile-client} details page in the OpenShift console, along with the mobile services associated with that {mobile-client}

//end::mobilecicd-service[]


// change to {runtimeconnector-service} maybe

= {custom-service}

//tag::runtimeconnector-service[]

The {custom-service} service allows you connect your mobile apps to your own back-end API servers.

* Bind your mobile client to custom back-end API services and business logic
* Ability to add custom configuration for a back-end service, which becomes accessible from your Mobile App

//end::runtimeconnector-service[]



// change to {device-security} maybe
= {device-security-service}
//tag::device-security-service[]

The {device-security-service} service allows you to easily configure and manage device security, and trust checks for your mobile application

* Perform a range of device trust checks on the mobile device, such as checking if the device is rooted, and allows you take proactive action based on the results
* Distribute SSL certificates with a mobile app to create a direct chain of trust (certificate pinning)

NOTE: {device-security-service} is not currently associated with an OpenShift service, so there are no provisioning or binding tasks associated with using {device-security-service}.

//end::device-security-service[]
