


// maybe change attr to {pushnotification-service}

= {unifiedpush-service} Service
//tag::pushnotification-service[]

The {unifiedpush-service} service allows you to send native push notifications to different mobile operating systems.

* Code once and push notifications to iOS and Android
* Push notifications to defined groups
* Push notifications to either iOS only or Android only
* Push notifications to different variants of a mobile app
* Push notifications from different back-end apps to the same mobile app

//end::pushnotification-service[]



= {metrics-service} Service
//tag::metrics-service[]

The {metrics-service} service allows you to gather metrics on mobile apps, device versions, device security checks and back-end mobile service usage.

* Monitor usage by version of mobile app, platform and SDK
* Monitor interactions with the Identity Management service

//end::metrics-service[]


// change to {identitymanagement-service} maybe 

= {keycloak-service}
//tag::identitymanagement-service[]

The {keycloak-service} service allows you to add authentication and authorization to your mobile app.

* Secure your mobile app using the industry standard OpenID Connect protocol
* Add access control to your app based on user’s group membership
* Easily implement SSO, multi-factor authentication and Social Login support
* Back-end support for identity brokering and user federation

//end::identitymanagement-service[]


//change to {mobilecicd-service} maybe 

= {mobile-ci-cd-service}
//tag::mobilecicd-service[]

The {mobile-ci-cd-service} service allows you to automate the building of your native and hybrid mobile app for both Android and iOS.

* Leverage your Jenkins expertise to manage and automate mobile builds.
* Containerised builds on OpenShift for Android
* Support for integrating macOS as build slaves for iOS builds
* Catch build errors early using automated builds

//end::mobilecicd-service[]


// change to {device-security} maybe
= {device-security-service}
//tag::device-security-service[]

The {device-security-service} service allows you to easily configure and manage device security, and trust checks for your mobile application

* Perform a range of device trust checks on the mobile device, such as checking if the device is rooted, and allows you take proactive action based on the results
* Distribute SSL certificates with a mobile app to create a direct chain of trust (certificate pinning)

NOTE: {device-security-service} is not currently associated with an OpenShift service, so there are no provisioning or binding tasks associated with using {device-security-service}.

//end::device-security-service[]



= {sync-service}
//tag::sync-service[]

The goal of {sync-service} is to make it easier for developers to build secure, production ready, real time APIs and applications with link:https://graphql.org/learn[GraphQL].

{sync-service} is a JavaScript framework that developers can use to add real time synchronization and enhanced offline capabilities to their mobile applications. {sync-service} includes two components - {sync-server} and {sync-client}.

{sync-server} is set of Node.js libraries that can be used to build a custom backend {sync-service} service using GraphQL.

{sync-client} is client side JavaScript library for building web and mobile applications backed by {sync-server}.

{sync-server} and {sync-client} are based off the popular link:https://www.apollographql.com/docs/[Apollo] framework and add additional components to solve common problems.

* Real Time Synchronisation
* Conflict Resolution
* Robust offline experience
* Authentication and Authorization (using the {keycloak-service} service)
* Metrics (using the AeroGear {metrics-service} Service)
* Audit Logging


//end::sync-service[]
