include::{partialsdir}/attributes.adoc[]

//[[downloading-the-mobile-services-configuration-file]]
= Downloading the Mobile Services Configuration File

. Navigate to your project in OpenShift.
. On the *Overview* screen, expand your {mobile-client} to view the *CLIENT INFO*.
. Copy the configuration to your clipboard.
. Save the contents of the clipboard to a new file called `mobile-services.json`.
. Follow the next specific additional instructions depending on your platform:

[role="primary"]
.Android

****

Locate this file at the following location in your application project:

`src/main/assets/mobile-services.json`

****

[role="secondary"]
.iOS

****

Locate this file at the following location in your application project:

`<app directory>/mobile-services.json`

****

[role="secondary"]
.Cordova

****

Locate this file in your application project and import it using `require`.

[source,javascript]
----
const aerogearConfig = require("./mobile-services.json");
----

Alternatively you can create a JavaScript object and use directly:

[source,javascript]
----
const aerogearConfig = /* Paste here the contents of the clipboard */;
----

****

[role="secondary"]
.Xamarin

****

Locate this file at the following location in your application project:

`Resources/mobile-services.json`

****
