

= Setting up {org-name} {product-name} on OpenShift

{product-name} run natively on link:https://www.openshift.org/[OpenShift, window="_blank"]. The installation script in the following steps installs {product-name} on OpenShift.

[[prerequisites]]
== Prerequisites

* OpenShift 3.11 instance
+
** This instance must have Service Catalog, Ansible Service Broker and Template Service Broker services installed.
+
** You need to have full access to this OpenShift instance, i.e. user with `cluster-admin` privileges.
+
NOTE: If you don't have OpenShift instance you can use `oc cluster up` or Minishift to xref:local-setup[setup OpenShift locally].

* link:https://www.openshift.org/download.html[OpenShift client tools, window="_blank"] version 3.11

* link:https://www.docker.com/[Docker, window="_blank"]

* A local mobile development environment for the platform you want to develop on.

* link:https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html[Ansible 2.7.x, window="_blank"] installed on the machine where you want to run the installation scripts from

[[procedure]]
== Procedure

=== Automated Install

. Clone the Mobile Services Installer repository:
+
The repository contains installation script for {org-name} {product-name}.
+
Clone this repo to your local machine and check out the {release-number} tag using:
+
[source,bash,subs="attributes"]
----
git clone https://github.com/aerogear/mobile-services-installer.git
cd mobile-services-installer
git checkout {release-number}
----

. Login to your OpenShift instance as user with `cluster-admin` privileges:
+
[source,bash]
----
$ oc login <OPENSHIFT_MASTER_URL>
----

. Change directory SELinux security context (RHEL/Fedora):
+
NOTE: This step is only required on RHEL/Fedora with SELinux enabled.
+
[source,bash]
----
$ chcon -Rt svirt_sandbox_file_t .
----

. In the same directory, run the installer:
+
[source,bash]
----
$ ansible-playbook install-mobile-services.yml
----
+

. Verify the installation:
+
.. Browse to the Web console of your OpenShift instance and log in.

.. Check that the _Mobile_ tab is displayed in the service catalog. If this tab is not displayed, wait a few minutes to make sure that the installation process has completed.

=== Manual Install

. Login to your OpenShift instance as user with `cluster-admin` privileges using `oc`
. Prepare the Custom Resource Definition file for mobile:
+
[source,bash,subs="attributes"]
----
cat > /tmp/crd.yaml << EOF
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mobileclients.mobile.k8s.io
spec:
  group: mobile.k8s.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: mobileclients
    singular: mobileclient
    kind: MobileClient
    shortNames:
    - mc
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            apiKey:
              type: string
              pattern: '(\w{8}-\w{4}-\w{4}-\w{4}-\w{11})'
            name:
              type: string
              pattern: '([\w-])'
            dmzUrl:
              type: string
              nullable: true
EOF
----
. Run the following commands to setup the Custom Resource on OpenShift:
+
[source,bash,subs="attributes"]
----
oc create -f /tmp/crd.yaml
oc create clusterrole mobileclient-admin --verb=create,delete,get,list,patch,update,watch --resource=mobileclients
oc adm policy add-cluster-role-to-group mobileclient-admin system:authenticated
----
. Update the configurations of Automation Service Broker to add new registries:
.. Edit the config map object using `oc`
+
[source,bash,subs="attributes"]
----
oc edit configmap broker-config -n openshift-automation-service-broker
----
.. Add the following new registries to the `registry` section of the config:
+
[source,yaml,subs="attributes"]
----
registry:
- type: dockerhub
  name: ag
  url: https://registry.hub.docker.com
  org: aerogearcatalog
  tag: 1.0.0
  white_list:
    - '.*-apb$'
  black_list:
    - '.*mobile-developer-console-apb$'
- type: dockerhub
  name: ag-mdc
  org: aerogearcatalog
  tag: 1.0.0-alpha
  url: https://registry.hub.docker.com
  white_list:
  - '.*mobile-developer-console-apb$'
----
.. Update the following attributes in the `openshift` section of the config:
+
[source,yaml,subs="attributes"]
----
openshift:
  image_pull_policy: Always
  sandbox_role: admin
----
.. Update the following attributes in the `broker` section of the config:
+
[source,yaml,subs="attributes"]
----
broker:
  launch_apb_on_bind: true
----
.. Save the configmap object, and restart the automation service broker:
+
[source,bash,subs="attributes"]
----
oc rollout latest openshift-automation-service-broker -n openshift-automation-service-broker
----

. Verify the installation:
+
.. Browse to the Web console of your OpenShift instance and log in.

.. Check that the _Mobile_ tab is displayed in the service catalog. If this tab is not displayed, wait a few minutes to make sure that the installation process has completed.

[id='additional-resources']
[discrete]
= Additional resources

[[local-setup]]
== Local OpenShift setup

You can run OpenShift locally on your machine. There are two scripts in Mobile Developer Console repository which will create the cluster using Minishift or `oc cluster up`, and enable {org-name} {product-name}.

NOTE: On Mac only Minishift is currently supported.

=== Prerequisites

[tabs]
====
Minishift::
+
--

* link:https://www.okd.io/minishift/[Minishift, window="_blank"]

* link:https://www.openshift.org/download.html[OpenShift client tools, window="_blank"] version 3.11

* link:https://www.docker.com/[Docker, window="_blank"]

* link:https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html[Ansible 2.7.x, window="_blank"] installed on the machine where you want to run the installation scripts from

--
oc cluster up::
+
--

* Linux

* link:https://www.openshift.org/download.html[OpenShift client tools, window="_blank"] version 3.11

* link:https://www.docker.com/[Docker, window="_blank"]

* link:https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html[Ansible 2.7.x, window="_blank"] installed on the machine where you want to run the installation scripts from

* Firewall configured:
+
[source,bash]
----
firewall-cmd --permanent --add-port=8443/tcp
firewall-cmd --permanent --add-port=8053/tcp
firewall-cmd --permanent --add-port=53/udp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --reload
----
====

=== Procedure

. Clone the Mobile Services Installer repository:
+
[source,bash,subs="attributes"]
----
git clone https://github.com/aerogear/mobile-services-installer.git
cd mobile-services-installer
git checkout {release-number}
----

. Run the installation script:
+
[tabs]
====
Minishift::
+
--
[source,bash]
----
$ ./scripts/minishift.sh
----
--
oc cluster up::
+
--
[source,bash]
----
$ ./scripts/oc-cluster-up.sh
----
====

. Copy cluster self-signed certificate:
+
When the script finishes it will save OpenShift's self-signed certificate to `/tmp/oc-certs/localcluster.crt`. Copy this file so you can later xref:showcase-apps.adoc#installing-on-device[install it to your mobile device].
+
This is needed so that your mobile app can communicate with OpenShift.

. Browse to the Web console of your local OpenShift instance, accept self-signed certificate and log in.
+
You can get OpenShift URL with:
+
[source,bash]
----
$ oc status
----
+
NOTE: Browser may redirect you to `localhost`. If that happens just enter the URL again and make sure to add `/console` at the end.
