= Setting up {org-name} {product-name} on OpenShift

{product-name} run natively on link:https://www.openshift.org/[OpenShift^].

// tag::excludeDownstream[]
[[prerequisites]]
.Prerequisites

* OpenShift 3.11 instance
+
** You need to have full access to this OpenShift instance, i.e. user with `cluster-admin` privileges.
+
NOTE: If you don't have OpenShift instance you can use `oc cluster up` or Minishift to xref:local-setup[setup OpenShift locally].
+
* If you are using Minishift, or if the OpenShift cluster doesn't already have a secret to access `https://registry.redhat.io`, then a service account is required to access `https://registry.redhat.io`.
+
** This is because IDM service uses productized images that are stored in this registry.
** To get a service account, go to `https://registry.redhat.io`, then click on `Service Accounts` tab on the top right corner, and then login using your Red Hat developer account. Click on `New Service Account` to create a new one. Take note of the username and password.
** For more information, please check link:https://docs.openshift.com/container-platform/3.11/install_config/configuring_red_hat_registry.html[Accessing and Configuring the Red Hat Registry].


* link:https://www.openshift.org/download.html[OpenShift client tools^] version 3.11

* link:https://www.docker.com/[Docker^]

* A local mobile development environment for the platform you want to develop on.

* link:https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html[Ansible 2.7.x^] installed on the machine where you want to run the installation scripts from

== Installing {product-name} using the installer script

. Clone the Mobile Services Installer repository:
+
The repository contains installation script for {org-name} {product-name}.
+
Clone this repo to your local machine and check out the {installer-release-number} tag using:
+
[source,bash,subs="attributes"]
----
git clone https://github.com/aerogear/mobile-services-installer.git
cd mobile-services-installer
git checkout {installer-release-number}
----

. Login to your OpenShift instance as user with `cluster-admin` privileges:
+
[source,bash]
----
$ oc login <OPENSHIFT_MASTER_URL>
----

. Change directory SELinux security context (RHEL/Fedora):
+
NOTE: This step is only required on RHEL/Fedora with SELinux enabled.
+
[source,bash]
----
$ chcon -Rt svirt_sandbox_file_t .
----

. In the same directory, run the installer:
+
[source,bash]
----
$ ansible-playbook install-mobile-services.yml -e registry_username="<registry_service_account_username>" -e registry_password="<registry_service_account_password>" -e openshift_master_url="<public_url_of_openshift_master>"
----
+
If the cluster can already access the Red Hat container registry, you can skip the part that sets up the pull secrets:
+
[source,bash]
----
$ ansible-playbook install-mobile-services.yml -e openshift_master_url="<public_url_of_openshift_master>" --skip-tags "pullsecret"
----

. You will also need to update the CORS configuration of the OpenShift cluster to allow the mobile developer console to communicate with the OpenShift API server (you only need to do this once).
+
** If you are using minishift, you should run [this script](./scripts/minishift-cors.sh).
** Otherwise, you should run [this playbook](./update-master-cors-config.yml) to update the master config of the OpenShift cluster. To run this playbook, you need to:
+
*** Get the host names of the master nodes by running `oc get nodes`. Take notes of the host names.
*** Copy [the sample hosts inventory file](./inventories/hosts.template), and update it to add the correct host names for master nodes.
*** You should also make sure that you can ssh into the master nodes from the workstation.
*** Run the playbook and specify the inventory file:
+
[source,bash]
----
$ ansible-playbook -i ./inventories/hosts update-master-cors-config.yml
----
+
NOTE: This playbook will restart the api and controller servers of the OpenShift cluster.

. Verify the installation:
+
.. Make sure all the pods are running in the `mobile-developer-services` project

// end::excludeDownstream[]

// tag::excludeDownstream[]
[id='additional-resources']
[discrete]
= Additional resources

[[local-setup]]
== Local OpenShift setup

You can run OpenShift locally on your machine. There are two scripts in Mobile Services Installer repository which will create the cluster using Minishift or `oc cluster up`, and enable {org-name} {product-name}.

NOTE: On Mac only Minishift is currently supported.

=== Prerequisites

[tabs]
====
Minishift::
+
--

* link:https://www.okd.io/minishift/[Minishift^]

* link:https://www.openshift.org/download.html[OpenShift client tools^] version 3.11

* link:https://www.docker.com/[Docker^]

* link:https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html[Ansible 2.7.x^] installed on the machine where you want to run the installation scripts from

--
oc cluster up::
+
--

* Linux

* link:https://www.openshift.org/download.html[OpenShift client tools^] version 3.11

* link:https://www.docker.com/[Docker^]

* link:https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html[Ansible 2.7.x^] installed on the machine where you want to run the installation scripts from

* Firewall configured:
+
[source,bash]
----
firewall-cmd --permanent --add-port=8443/tcp
firewall-cmd --permanent --add-port=8053/tcp
firewall-cmd --permanent --add-port=53/udp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --reload
----
====

=== Procedure

. Clone the Mobile Services Installer repository:
+
[source,bash,subs="attributes"]
----
git clone https://github.com/aerogear/mobile-services-installer.git
cd mobile-services-installer
git checkout {installer-release-number}
----

. Run the installation script:
+
[tabs]
====
Minishift::
+
--
[source,bash]
----
$ export REGISTRY_USERNAME=<registry_service_account_username>
$ export REGISTRY_PASSWORD=<registry_service_account_password>
$ ./scripts/minishift.sh
----
--
oc cluster up::
+
--
[source,bash]
----
$ export REGISTRY_USERNAME=<registry_service_account_username>
$ export REGISTRY_PASSWORD=<registry_service_account_password>
$ ./scripts/oc-cluster-up.sh
----
====

. Copy cluster self-signed certificate:
+
When the script finishes it will save OpenShift's self-signed certificate to `/tmp/oc-certs/localcluster.crt`. Copy this file so you can later xref:showcase-apps.adoc#installing-on-device[install it to your mobile device].
+
This is needed so that your mobile app can communicate with OpenShift.

. Browse to the Web console of your local OpenShift instance, accept self-signed certificate and log in.
+
You can get OpenShift URL with:
+
[source,bash]
----
$ oc status
----
+
NOTE: Browser may redirect you to `localhost`. If that happens just enter the URL again and make sure to add `/console` at the end.
// end::excludeDownstream[]
