//[[using-self-signed-certificates-in-mobile-clients]]
= Using Self-Signed Certificates in Mobile Apps

NOTE: Before you can run a mobile app and connect to {product-name}, you must configure self-signed certificates on the mobile device.

Throughout the development lifecycle of a mobile app, a common
requirement is to integrate and connect with back-end
services in a secure manner. This is achieved using SSL/TLS.

However, in order for the client device to connect over SSL/TLS, it needs to trust the
certificates used by the back-end services, which are signed by a certificate authority.
Most client devices have a list of well-known and trusted certificate authorities pre-installed and this allows the client devices to verify the certificates used by the back-end services.

However, this normally doesn't work in a development environment, such as a local OpenShift cluster as it uses self-signed certificates which are not signed by any of the trusted certificate authorties. This means by default the client devices won't be able to establish secure connections with the back-end services that are running on a local OpenShift cluster.

To work around the problem, you must manually extract the root certificate from the cluster, install it on the device and mark it as trusted.

[[extracting-root-ca]]
== 1. Extracting the OpenShift Root Certificate Authority Cert

.. Log into OpenShift as the admin user:
+
[source,bash]
----
$ oc login -u system:admin
----

.. Run the following command:
+
[source,bash]
----
$ oc get secret router-certs --template='{{index .data "tls.crt"}}' -n default  |  \
base64 --decode | sed -e '1,/^-----END RSA PRIVATE KEY-----$/ d'  > /tmp/localcluster.crt
----
+
The resulting file is located in the `/tmp` directory.

[[installing-on-device]]
== 2. Installing the OpenShift Root Certificate Authority Cert on a Device

[tabs]
====
// tag::excludeDownstream[]
Android::
+
--
.. https://support.google.com/android/answer/2819522?hl=en[Set screen lock] on the mobile device to ensure the certificate can be installed.

.. Copy the file to your device using one of the following methods:
+
* Email attachment (Recommended) - Simply email the certificate to an address
accessible from the device and download the attachment.
* Cloud service - Use a cloud storage service such as Dropbox or Google
Drive which is accessible from the device, browse to the certificate and
proceed to download it.
* USB - Attach the device to the machine hosting
OpenShift via USB and drag the certificate to a devices file system. Here is an https://support.google.com/nexus/answer/2840804?hl=en[example guide for Google Nexus devices]. It may be different for other devices.
* link:https://developer.android.com/studio/command-line/adb[Android Debug Bridge^] (adb) - Use the adb push command to push the certificate to device or emulator:
+
----
$ adb push /tmp/localcluster.crt /sdcard/Download/localcluster.crt
----
.. Add the certificate to your device:
+
If you are using the email or cloud service approach, once the certificate file is downloaded, you will be prompted by the Android system automatically to install the file. You can simply follow the instructions to complete the process.
+
However, if you are using the USB approach, you will need to install the certificate manually: go to Settings > Security > Install from storage, tap on the copied certificate file and Android system should detect the
certificate and let you add it to the device. Here is https://support.google.com/nexus/answer/2844832?hl=en[a sample guide for Google Nexus devices].
--
iOS::
+
--
.. Enable https://support.apple.com/en-us/ht204060[Passcode] or https://support.apple.com/en-us/ht201371[TouchID] protection on the mobile device to ensure the certificate can be installed.
.. Copy the file to your device using one of the following methods:
+
* Email attachment (Recommended) - Simply email the certificate to an address
accessible from the device and download the attachment.
* Cloud service - Use a cloud storage service such as Dropbox or Google
Drive which is accessible from the device, browse to the certificate and
proceed to download it.
.. Add the certificate to your device:
+
When you download the certificate, the
device should automatically detect a profile. Simply follow the on
screen instructions to install it.
+
NOTE: Versions iOS 10.3 and later require an additional step to trust the now
installed certificate. Instructions can be found on the
https://support.apple.com/en-us/HT204477[Apple support site]
--
// end::excludeDownstream[]
====
