= Querying a Data Sync server using a Data Sync client

.Prerequisites
* You have Node.js and npm installed.
* You have created an empty web project that supports ES6, for example, using the link:https://webpack.js.org/guides/getting-started/[webpack getting started] guide.
* You have completed the server getting started guide and the application is running.

This section describes how to use the {sync-client} to create mobile and web applications that can communicate with the Voyager server application.

Data Sync provides JavaScript libraries which integrate your javascript app using with a server that also uses Data Sync.  The client libraries are based on the link:https://www.apollographql.com/docs/react/api/apollo-client.html[Apollo client].

== Hello World Sync

Connecting our client to the server "Hello World" example. You will add the libraries to your mobile project, configure the client classes, connect to the server, and confirm that it works.

.Add our libraries to your javascript client,
[source,bash]
----
npm install @aerogear/voyager-client
----

Below is a simple code example to connect to and query our {sync-server}.  To configure the client, a configuration object should be used. At a minimum, the `httpUrl` field is required and it is the url of the Voyager server application. If the client app uses subscription as well, then the `wsUrl` field is required too.

Core to connect to and query our server application would look like the following:

.src/index.js
[source,javascript]
----
// gql is a utility function that handles gql queries
//import gql from 'graphql-tag';

import { OfflineClient } from '@aerogear/voyager-client';

// For our client application, we will connect to the local service.
let config = {
  httpUrl: "http://localhost:4000/graphql",
  wsUrl: "ws://localhost:4000/graphql",
}

async function helloWorld() {

  // Actually create the client
  let offlineClient = new OfflineClient(config);
  let client = await offlineClient.init();

  // Execute the hello query
  client.query({
      fetchPolicy: 'network-only',
      query: gql`{
  addressBook {
    id
    name
    address
  }
}`
    })
    //Print the response of the query
    .then( ({data}) => {
      console.log(data.hello)
    });
}

helloWorld();
----

You can build and run this code in your project. You should see "Hello world" in your JavaScript console. The server and client can now communicate.
