//':context:' is a vital parameter. See: http://asciidoctor.org/docs/user-manual/#include-multiple
[id='ref-data-sync-terminology-{context}']
= Data Sync terminology

This section describes terminology that is associated with Data Sync.

.Data Sync terminology

Data Sync framework:: Data Sync is a JavaScript framework that enables a developer to add the capability to synchronize data in real-time for both mobile and web clients.
The Data Sync framework consists of two components, the _Sync Server_ and the _Sync Client_.

Sync Server:: The Sync Server is a framework for building Node.js based GraphQL API.

Sync Client:: The Sync Client is a JavaScript client offering client side extensions and server side integration. The Sync Client can be integrated into frameworks such as React and Angular.

Data sources:: Data Sync framework is typically used in conjunction with a data source for data persistence however, an app built using the Data Sync framework works without a data source.

GraphQL:: A query language for your API, and a server-side runtime for executing queries that use a type system. For more information, see link:https://graphql.org/learn[GraphQL].
