[id="realtime-updates-{context}"]
= Realtime Updates

A core concept of the GraphQL specification is an operation type called `Subscription`, they provide a mechanism for real time updates.
To enable Subscriptions on the server, create an appropriate schema similar to the following example.

.Procedure

. Create a schema to support subscriptions.
+
For example, in the following schema a `Task` type is defined, followed by required Mutations and Subscriptions.
When a new task is created, the resolver for that task publishes the result of this mutation to the `TaskCreated` channel.
+
[source,javascript]
----
const { gql } = require('@aerogear/voyager-server')

const typeDefs = gql `
type Task {
  id: ID!
  title: String!
  description: String!
}

type Mutation {
  createTask(title: String!, description: String!): Task
}

type Subscription {
  taskCreated: Task
}
`

const resolvers = {
    Mutation: {
        createTask: async (obj, args, context, info) => {
            const result = tasks.create(args)
            pubSub.publish('TaskCreated', {
                taskCreated: result
              });
            return result
        }
    },
    Subscription: {
        taskCreated: {
            subscribe: () => pubSub.asyncIterator('TaskCreated')
        }
  },
}
----
+
NOTE: The pubSub mechanism used in the above example is deliberately ommited to focus on the GraphQL aspects of
Subscriptions. For more information on the available PubSub implementations see: link:https://www.apollographql.com/docs/apollo-server/features/subscriptions.html#PubSub-Implementations[PubSub Implementations].

. Use the `subscriptions-transport-ws` package to set up the server.
+
For more information on how to use and configure `SubscriptionServer` see the link:https://www.apollographql.com/docs/graphql-subscriptions/setup.html#subscription-server[Apollo Subscription Server documentation].
+
Using the example server described in xref:sync-server-getting-started[] you can add subscriptions as follows by introducing http and wraping our express app:
+
[source,javascript]
----
const http = require('http')
const { SubscriptionServer } = require('subscriptions-transport-ws')
const { execute, subscribe } = require('graphql')

const httpServer = http.createServer(app)

server.applyMiddleware({ app })

httpServer.listen(4000, () => {
  new SubscriptionServer ({
    execute,
    subscribe,
    schema: server.schema
  }, {
    server: httpServer,
    path: '/graphql'
  })
})

----

NOTE: For information on how to protect this subscription server with {keycloak-service} see xref:sync-server-auth[].

.Additional Information

* For more information on GraphQL subscriptions, see the link:https://www.apollographql.com/docs/apollo-server/features/subscriptions.html[Subscriptions documentation].

* For documentation on how to use Subscriptions on your client, see xref:sync-js-client-realtime-updates[Realtime Updates].
