[id="realtime-updates-{context}"]
= Configuring your server for real-time updates

To enable Subscriptions on the server:

* Configure SubscriptionServer using voyager-subscriptions.
+
This allows you create GraphQL subscription types in your schema. 
* Configure a Publish Subscribe Mechanism.
+
This provides a channel to push updates to your client.

* Define Subscriptions in the Schema and implement subscription resolvers.

The follow code shows typical code for a Data Sync Server without subscriptions:

[%collapsible]
====
[source,js]
----
const apolloServer = VoyagerServer({
  typeDefs,
  resolvers
})

const app = express()
apolloServer.applyMiddleware({ app })

app.listen({ port }, () =>
  console.log(`🚀 Server ready at http://localhost:${port}${apolloServer.graphqlPath}`)
)
----
====


.Procedure

To enable subscriptions for the Data Sync server:

WARNING: This example uses the default `PubSub` provided by `apollo-server`. This is an in memory implementation which is useful for prototyping but not suitable for production. We recommend using link:npm.im/@aerogear/graphql-mqtt-subscriptions[MQTT PubSub] in production.

. Configure SubscriptionServer using `@aerogear/voyager-subscriptions`
+
[%collapsible]
====
[source,js]
----
const { createSubscriptionServer } = require('@aerogear/voyager-subscriptions')

const apolloServer = VoyagerServer({
  typeDefs,
  resolvers
})

const app = express()
apolloServer.applyMiddleware({ app })

const server = app.listen({ port }, () =>
  console.log(`🚀 Server ready at http://localhost:${port}${apolloServer.graphqlPath}`)

  createSubscriptionServer({ schema: apolloServer.schema }, {
    server,
    path: '/graphql'
  })
)
----
====
+
The `createSubscriptionServer` code:
+
* returns a `SubscriptionServer` instance 
* installs handlers for 
** managing websocket connections
** delivering subscriptions on the server
* provides integrations with other modules such as `@aerogear/voyager-keycloak`.
+
See https://npm.im/subscriptions-transport-ws[subscriptions-transport-ws] module for more information about arguments and options.
+

. Configure a Publish Subscribe Mechanism
+
Subscriptions depend on a https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern[publish subscribe] mechanism to generate the events that notify a subscription. There are https://www.apollographql.com/docs/apollo-server/features/subscriptions/#pubsub-implementations[several `PubSub` implementations] available based on the `PubSubEngine` interface.
+
[%collapsible]
====
[source,js]
----
const { PubSub } = require('apollo-server')

const pubsub = new PubSub()
----
====
+
. Define Subscriptions in the Schema and Implement Subscription Resolvers 
+
Subscriptions are a root level type. They are defined in the schema similar to `Query` and `Mutation`. For example, in the following schema, a `Task` type is defined, as well as required Mutations and Subscriptions.
+
[%collapsible]
====
----
type Subscription {
  taskCreated: Task
}

type Mutation {
  createTask(title: String!, description: String!): Task
}

type Task {
  id: ID!
  title: String!
  description: String!
}
----
====
+
Inside the resolver map, Subscription resolvers return an `AsyncIterator,` which listens for events.
To generate an event, the `publish` method is used on the `pubsub` implementation. `pubsub.publish` can be called anywhere but it is usually called inside a Mutation resolver.
+
In the example, when a new task is created, the `createTask` resolver publishes the result of this mutation to the `TaskCreated` channel.
+
[%collapsible]
====
[source,js]
----
const TASK_CREATED = 'TaskCreated'

const resolvers = {
  Subscription: {
    taskCreated: {
      subscribe: () => pubSub.asyncIterator(TASK_CREATED)
    }
  },
  Mutation: {
    createTask: async (obj, args, context, info) => {
      const task = tasks.create(args)
      pubSub.publish(TASK_CREATED, { taskCreated: task })
      return task
    }
  },
}
----
====

NOTE: This subscription server does not enforce authentication or authorization. See {keycloak-service} see xref:sync-server-auth[].

.Additional Information

* For more information on GraphQL subscriptions, see the link:https://www.apollographql.com/docs/apollo-server/features/subscriptions.html[Subscriptions documentation].

* For documentation on how to use Subscriptions on your client, see xref:sync-js-client-realtime-updates[Realtime Updates].


