[id="mqtt-pubsub-{context}"]
= Configuring a Publish Subscribe mechanism

== Using the Apollo PubSub mechanism

The xref:realtime-updates-{context}[] section describes how to set up the default `PubSub` provided by `apollo-server`. For a production system, you require link:npm.im/@aerogear/graphql-mqtt-subscriptions[MQTT PubSub] in production.


== Using the MQTT PubSub mechanism

The https://npm.im/@aerogear/graphql-mqtt-subscriptions[`@aerogear/graphql-mqtt-subscriptions`] module provides an `AsyncIterator` interface used for xref:realtime-updates-{context}[implementing subscription resolvers]
It connects the {sync-service} server to an MQTT broker to support horizontally scalable subscriptions.

.Procedure

. Initialize an MQTT client and pass it into `@aerogeaar/graphql-mqtt-subscriptions`
+
[%collapsible]
====
[source,js]
----
const mqtt = require('mqtt')
const { MQTTPubSub } = require('@aerogear/graphql-mqtt-subscriptions')

const client = mqtt.connect('mqtt://test.mosquitto.org', {
  reconnectPeriod: 1000,
})

const pubsub = new MQTTPubSub({
  client
})
----
====

In the example, an mqtt client is created using `mqtt.connect` and then this client is passed into an `MQTTPubSub` instance. This `pubsub` can now be used to publish and subscribe to events in the server.

.Additional Information

* Read the https://www.npmjs.com/package/mqtt#connect[documentation for `mqtt.connect`].
* Read the https://npmjs.com/package/@aerogear/graphql-mqtt-subscriptions[documentation for MQTTPubSub]