= Mobile Services Documentation

== Getting Started

The OpenShift Ansible Broker is used to provision Mobile Services to an OpenShift cluster. To add the Aerogear Mobile Services APBs (Ansible Playbook Bundles) to your OpenShift cluster, follow the guide for link:adding-services-to-ansible-broker.adoc[Adding Mobile Services to the OpenShift Ansible Broker]. This will allow you to provision services, such as the Metrics Service, from the OpenShift Catalog.

== Metrics Service

The metrics service provides monitoring and metrics for provisioned mobile services.

The service consists of link:https://prometheus.io/[Prometheus] and link:https://grafana.com/[Grafana] with an OAuth Proxy
tied to link:https://github.com/aerogear/mobile-docs/blob/master/services/giving-an-openshift-user-access-to-metrics.adoc[openshift permissions], 
for authentication and authorization. It automates the gathering and display of service metrics by using features in Openshift, 
link:https://github.com/aerogear/mobile-docs/blob/master/services/making-mobile-services-discoverable-by-metrics.adoc[annotations]
and link:https://github.com/aerogear/mobile-docs/blob/master/services/working-with-grafana-dashboards.adoc[configMaps], 
to allow the discovery of service metrics and visualization of data. The metrics service makes it easy to monitor provisioned mobile services and 
link:https://github.com/aerogear/mobile-docs/blob/master/services/manually-adding-services-to-metrics.adoc[custom services] in your project. 

=== Features

* Metrics gathering using Prometheus.
* Full graphing and visualization power of Grafana.
* Automatic metrics scraping of configured mobile services.
* Simple addition of Custom Services.
* ConfigMap based Grafana dashboard definitions in JSON format.
* Authorization and authentication through Oauth proxies.

=== Videos

* link:https://www.youtube.com/watch?v=xWFWUcuZPaQ[Overview video on youtube]

video::xWFWUcuZPaQ[youtube]