= Working with Grafana Dashboards

== Prerequisites

* OpenShift Origin >= 3.7
** https://docs.openshift.org/latest/install_config/index.html
* Metrics service deployment from the Service Catalog
** https://github.com/aerogearcatalog/metrics-apb

== Grafana Dashboards

The metrics service is made up of https://prometheus.io/[Prometheus] and https://grafana.com/[Grafana]. 
Prometheus is used to gather metrics data from other services and Grafana is used to visualise the metrics.

A Grafana dashboard allows you to arrange panels and charts together to provide a visual overview of your metrics. 
Please consult Grafana's http://docs.grafana.org/guides/getting_started/[Getting Started] guide for an introduction to dashboards. 

By default, any time you provision an AeroGear service from the OpenShift Service Catalog, a dashboard that shows metrics about that service will be added to Grafana.
In addition, you can create and modify your own dashboards.

Here are some reasons why you might create your own dashboard:

* You want to visualize metrics from your own apps and backend services.
* You want additional metrics from AeroGear services that are not displayed by default.
* You want additional metrics from OpenShift that are not displayed by default.

== Creating Grafana Dashboards

Creating Dashboards for Grafana is an interactive process. Dashboards are created in a 'Drag and Drop' fashion using the Grafana UI.
Please consult the http://docs.grafana.org/[Official Grafana Documentation] to learn about building Grafana dashboards. 
The Grafana documentation provides plenty of tutorials and videos for creating dashboards.

== Importing Grafana Dashboards

Under the hood, all Grafana dashboards are represented by a JSON definition. Dashboards can be imported and exported using the JSON definition.
See the Grafana documentation on http://docs.grafana.org/reference/export_import/[importing and exporting dashboards] through the Grafana UI.

== Customising the AeroGear Dashboards

As mentioned previously, any time you deploy an AeroGear service from the Service Catalog, a dashboard that shows metrics about that service is added to Grafana.

**You should not edit these dashboards directly.** Instead you should clone the dashboard and make your changes to the cloned dashboard.

There is a good reason for this. Over time, the AeroGear services on the Service Catalog are updated which may also include updates to the provided dashboards. 
If you modify these dashboards directly, your changes will be lost when you receive an update.

=== Cloning a Dashboard

* Open the Dashboard you wish to clone.
* Click the settings icon in the dashboard controls. This brings you to a settings screen.
* Select the 'Save As' option and enter in a new name for the dashboard.
* You now have a copy of the original dashboard.

