

include::configuring-dev-env-security.adoc[]

== Setting up {device-security-service} service SDK

=== Importing the libraries

[tabs]
====
// tag::excludeDownstream[]
Android::
+
--
. Add the following dependency in your app's *build.gradle*:
+
[source,groovy,subs="attributes"]
----
dependencies {
    implementation 'org.aerogear:android-security:{android-sdk-release-number}'
}
----

. Get an instance of `SecurityService` to start using the SDK.
+
[source,java]
----
SecurityService securityService = new SecurityService();
----
+
NOTE: It is user responsibility to manage the `SecurityService` lifecycle.

--
iOS::
+
--

. Add the dependency to your *Podfile*
+
[source,ruby,subs="attributes"]
----
target '[TARGET NAME]' do
    pod 'AGSSecurity', '{ios-sdk-release-number}'
end
----

. Update the dependencies by running in your terminal
+
[source,bash]
----
$ pod install
----

. Import `AGSSecurity` and instantiate the `SecurityService` to start using the SDK
+
[source,swift]
----
import AGSSecurity

let security = AGSSecurity()
----
+
NOTE: Any subsequent call to AGSSecurity returns the same instance of the `SecurityService`.

--
// end::excludeDownstream[]
Cordova::
+
--

. Install the link:https://www.npmjs.com/package/@aerogear/security[AeroGear Security] package from link:https://www.npmjs.com/[NPM^]
+
[source,bash]
----
$ npm install @aerogear/security
----

. Add the link:https://www.npmjs.com/package/@aerogear/cordova-plugin-aerogear-security[AeroGear Security plugin^] for Cordova:
+
[source,bash]
----
$ cordova plugin add @aerogear/cordova-plugin-aerogear-security
----

. Import and instantiate `SecurityService` to start using the SDK:
+
[source,javascript]
----
const SecurityService = require("@aerogear/security");

const securityService = new SecurityService();
----
+
NOTE: Any new instantiation of `SecurityService` returns the same instance.

--
// tag::excludeDownstream[]
Xamarin::
+
--

. Install link:https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools[NuGet^]

. Install the link:https://www.nuget.org/packages/AeroGear.Mobile.Security[AeroGear Security^] package
+
[source,bash,subs="attributes"]
----
$ dotnet add package AeroGear.Mobile.Security --version {xamarin-sdk-release-number}
----

. Install the specific packages for Android:
+
[source,bash,subs="attributes"]
----
$ dotnet add package AeroGear.Mobile.Security.Platform.Android --version {xamarin-sdk-release-number}
----
+
And for iOS:
+
[source,bash,subs="attributes"]
----
$ dotnet add package AeroGear.Mobile.Security.Platform.iOS --version {xamarin-sdk-release-number}
----

. Initialize the SDK by adding the following line to your Android application's *MainActivity.cs*:
+
[source,c#]
----
protected override void OnCreate(Bundle savedInstanceState)
{
    base.OnCreate(savedInstanceState);

    SecurityService.InitializeService();
    // ...
}
----
+
And to your iOS application's *AppDelegate.cs*:
+
[source,c#]
----
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
{
    SecurityService.InitializeService();
    // ...
}
----

. Get an instance of `SecurityService` to start using the SDK:
+
[source, c#]
----
var securityService = MobileCore.GetService<SecurityService>();
----
+
NOTE: Any subsequent call to MobileCore#getInstance returns the same instance of `SecurityService`.
--
// end::excludeDownstream[]
====
