//':context:' is a vital parameter. See: http://asciidoctor.org/docs/user-manual/#include-multiple
:context: ref_terminology_{device-security-service}

[id='{context}_ref_terminology']

= {device-security-service} Terminology

This section describes terminology that is associated with {device-security-service}.

Root Access Detection (ROOT_ENABLED)::
Use it to help prevent your app running in a device that has been rooted/jailbroken. A device is considered rooted if *any* of the following are true:

- A custom key has been used to sign the kernel
- The `su` binaries are present

[tabs]
====
// tag::excludeDownstream[]
Android::
+
--
`DeviceChecks.ROOT_ENABLED`.

This function uses the link:https://github.com/scottyab/rootbeer[Rootbeer^] library to check if root access is present on the device.
--
iOS::
+
--
This check is not available for iOS.
--
// end::excludeDownstream[]
Cordova::
+
--
This check is not available for Cordova.
--
// tag::excludeDownstream[]
Xamarin::
+
--
This check is not available for Xamarin.
--
// end::excludeDownstream[]
====

Developer Mode Detection (DEVELOPER_MODE_ENABLED)::
To detect if Developer Mode has been enabled on the device the `DeviceCheckType#DEVELOPER_MODE_ENABLED` function can be used. This function uses Android’s link:https://developer.android.com/reference/android/provider/Settings.html[Settings^] class.

Debugger Detection (DEBUGGER_ENABLED)::
To detect if an Android debugger is attached to the app the `DeviceCheckType#DEBUGGER_ENABLED` function can be used. This function uses Android’s link:https://developer.android.com/reference/android/os/Debug.html[Debug^] class.

Emulator Detection (IS_EMULATOR)::
To detect if the app is being run on an emulator the `DeviceCheckType#IS_EMULATOR` function can be used. This function uses Android’s link:https://developer.android.com/reference/android/os/Build.html[Build^] class.

Device Lock Detection (SCREEN_LOCK_ENABLED)::
To detect if a device has a lock screen set (with pin, fingerprint, pattern) the `DeviceCheckType#SCREEN_LOCK_ENABLED` function can be used. This function uses Android’s link:https://developer.android.com/reference/android/app/KeyguardManager.html[KeyguardManager^] class.

App Data Backup Detection (BACKUP_ENABLED)::
To detect whether the application’s data is configured to be synchronized across devices the `DeviceCheckType#BACKUP_ENABLED` function can be used. The link:https://developer.android.com/guide/topics/manifest/application-element.html[allowBackup^] flag determines whether to allow the application to participate in the backup and restore infrastructure, which might be interesting to avoid depending on your app’s needs.

Device Encryption Detection (ENCRYPTION_ENABLED)::
To detect whether the devices' filesystem is encrypted the `DeviceCheckType#ENCRYPTION_ENABLED` function can be used. This function uses Android’s link:https://developer.android.com/reference/android/app/admin/DevicePolicyManager.html[DevicePolicyManager^] class.
