// tag::excludeDownstream[]
include::../_partials/attributes.adoc[]
// end::excludeDownstream[]



=== Data Sync SDK for Native Android and iOS

---

The Data Sync feature for the Android and iOS SDKs are not fully functional. It is necessary to use the Apollo client for Android and iOS directly for the features described below.

General information for GraphQL can be found here: https://www.howtographql.com/


*Features*
^^^^^^^^^^

*Query*

Communicating with the GraphQL server starts with creating and configuring the Apollo client. This is accomplished by using the Apollo client for Android and iOS.

[tabs]
====
Android::
+
[source,text]
--
Performing queries against the custom GraphQL schema requires the use of an Android Apollo client object. Information on how to use the Apollo client is at https://www.apollographql.com/docs/android/essentials/queries/
--
iOS::
+
[source,text]
--
Performing queries against the custom GraphQL schema requires the use of an Apollo client object. Information on how to use the Apollo client is at https://www.apollographql.com/docs/ios/fetching-queries/
--
====

---

*Mutations*

Mutating data (CRUD operations) against the custom GraphQL schema.

[tabs]
====
Android::
+
[source,text]
--
Inserting, modifying, and deleting data (mutations) against the custom GraphQL schema requires the use of an android Apollo client object. Information on how to use the Apollo client to query data is at https://www.apollographql.com/docs/android/essentials/mutations/
--
iOS::
+
[source,text]
--
Inserting, modifying, and deleting data (mutations) against the custom GraphQL schema requires the use of an Android Apollo client object. Information on how to use the Apollo client for mutations is at https://www.apollographql.com/docs/ios/mutations/
--
====

---

*File Upload*

The Apollo client can also be used to upload file from a mobile Android and iOS device.
[tabs]
====
Android::
+
[source,text]
--
Uploding files from a mobile client against the custom GraphQL schema requires the use of an Android Apollo client object. Information on how to use the Apollo client to upload files is at https://github.com/apollographql/apollo-android#support-file-upload
--
iOS::
+
[source,text]
--
Uploding files from a mobile client against the custom GraphQL schema requires the use of an iOS Apollo client object. Information on how to use the Apollo client to upload is at https://www.apollographql.com/docs/ios/
--
====


*Realtime Updates*

The Apollo GraphQL client supports realtime updates

[tabs]
====
Android::
+
[source,text]
--
Apollo GraphQL supports subscriptions to realtime updates. Information on how to use the Apollo client to upload is at https://learn.hasura.io/graphql/android/subscriptions/1-subscription
--
iOS::
+
--
Apollo GraphQL supports subscriptions to realtime updates. Information on how to use the Apollo client to upload is at https://github.com/apollographql/apollo-ios
--
====

---

*Additional Information*

. Client SDK information: https://blog.apollographql.com/one-graphql-client-for-javascript-ios-and-android-64993c1b7991
. Information on the Apollo GraphQL client for android can be found here: https://www.apollographql.com/docs/android/[appollo client for android].
