// tag::excludeDownstream[]
include::../_partials/attributes.adoc[]
// end::excludeDownstream[]



=== Data Sync SDK for Native Android and IOS

---

Although the javascript SDK for Data Sync is fully functional and currently supported, the Data Sync android and ios SDKs are neither fully functional nor currently supported. As of the writing of this document, it may be necessary to use the Apollo client for android and ios directly for the features described below.
+
General information for GraphQL can be found here: https://www.howtographql.com/


*Features*
^^^^^^^^^^

*Query*

Communicating with the GraphQL server starts with creating and configuring the appollo client. This is accomplished by using the Apollo client for android.

[tabs]
====
Android::
+
[source,text]
--
Performing queries against the custom GraphQL schema requires the use of an android Apollo client object. Aerogear does provide support for queries in their android SDK. However, it is possible to use the android Apollo API directly. Information on how to use the Apollo client is at https://www.apollographql.com/docs/android/essentials/queries/
--
iOS::
+
[source,text]
--
Performing queries against the custom graphql schema requires the use of an Apollo client object. Aerogear does provide support for queries in their ios SDK. However, it is possible to use the ios Apollo API directly. Information on how to use the Apollo client is at https://www.apollographql.com/docs/ios/fetching-queries/
--
====

---

*Mutations*

Mutating data against the custom graphql schema.

[tabs]
====
Android::
+
[source,text]
--
Mutating data against the custom graphql schema requires the use of an android Apollo client object. Aerogear does provide support for mutations in their android SDK. However, it is possible to use the android Apollo API directly. Information on how to use the Apollo client to query data is at https://www.apollographql.com/docs/android/essentials/mutations/
--
iOS::
+
[source,text]
--
Mutating data against the custom graphql schema requires the use of an android Apollo client object. Aerogear does provide support for mutations in their ios SDK. However, it is possible to use the android Apollo API directly. Information on how to use the Apollo client to use mutations is at https://www.apollographql.com/docs/ios/mutations/
--
====

---

*File Upload*

The Apollo client wrapper classes can also be used to subscribe to and receive live streams from the specified url.
[tabs]
====
Android::
+
[source,text]
--
Uploding files from mobile client graphql schema requires the use of an android Apollo client object. Aerogear does provide support for mutations in their android SDK. However, it is possible to use the android Apollo API directly. Information on how to use the Apollo client to upload files is at https://github.com/apollographql/apollo-android#support-file-upload
--
iOS::
+
[source,text]
--
Uploding files from mobile client graphql schema requires the use of an android Apollo client object. Aerogear does provide support for mutations in their ios SDK. However, it is possible to use the android Apollo API directly. Information on how to use the Apollo client to upload is at https://www.apollographql.com/docs/ios/
--
====


*Realtime Updates*

The Apollo GraphQL client supports realtime updates

[tabs]
====
Android::
+
[source,text]
--
ApolloQL supports subscriptions to realtime updates. Aerogear does provide support for subscriptions in their android SDK. However, it is possible to use the android Apollo API directly. Information on how to use the Apollo client to upload is at https://learn.hasura.io/graphql/android/subscriptions/1-subscription
--
iOS::
+
--
ApolloQL supports subscriptions to realtime updates. Aerogear does provide support for subscriptions in their android SDK. However, it is possible to use the ios Apollo API directly. Information on how to use the Apollo client to upload is at https://github.com/apollographql/apollo-ios
--
====

---

*Additional Information*

. Client SDK information: https://blog.apollographql.com/one-graphql-client-for-javascript-ios-and-android-64993c1b7991
. Information on the Apollo GraphQL client for android can be found here: https://www.apollographql.com/docs/android/[appollo client for android].
