// tag::excludeDownstream[]
include::../_partials/attributes.adoc[]
// end::excludeDownstream[]



=== Data Sync SDK for Native Android and IOS

---

The support for native android and ios data sync clients is a wrapper for the apollo client, thus eliminating the need for custom apps to deal with the boilerplate code necessay to construct and configure the apollo client. The wrapper classes also provide the basic functions needed to query and mutate data against the custom graphQL api and subscribe to live streams.

*Examples*
^^^^^^^^^^

*Query*

Communicating with the GraphQL server starts with creating and configuring the appollo client. This is accomplished by using the android or ios wrapper classes. These classes eliminate the need to write creation and configuration boilerplate code. Examples of how to query for data against the custome graphQL API are shown below:

[tabs]
====
GraphQL Schema::
+
[source,graphql]
--
// The schema snippet defines the graphql api. 
// The graphql/android build creates a java object the apollo client uses to query and mutate data against.

query FeedQuery($type: FeedType!, $limit: Int!) {
  feedEntries: feed(type: $type, limit: $limit) {
    id
    repository {
      name
      full_name
      owner {
        login
      }
    }
    postedBy {
      login
    }
  }
}
--
Android::
+
[source,java]
--
import org.aerogear.mobile.sync.SyncClient
import com.apollographql.apollo.api.Operation;

// Treat SyncClient as a Singleton and use the static "instance" of SyncClient

SyncClient client = SyncClient.getInstance();
FeedQuery query = FeedQuery.builder()
                               .limit(10)
                               .type(FeedType.HOT)
                               .build()
SyncQuery sq = client.query(query);
Operation.data results = sq.execute();
--
iOS::
+
--

. Add the dependency to your Podfile
+
[source,ruby]
----
target '[TARGET NAME]' do
    pod 'AGSSync', '[VERSION]'
end
----

. Update the dependencies
+
[source,bash]
----
$ pod install
----

. Import the SDK
+
[source,swift]
----
import AGSSync
----

. Get a reference of Apollo Client
+
[source,swift]
----
import AGSSync

 ...
/**
   get a reference of ApolloClient
 */

 var apollo = AGSSync.client
----
. Use the Apollo Client to make query against the Apollo server
https://www.apollographql.com/docs/ios/fetching-queries/
--
====

---

*Mutations*

The Apollo client wrapper classes can also be used to modify data in the backend data store against the custom graphQL API.

[tabs]
====
GraphQL Schema::
+
[source,graphql]
--
// The graphql schema snippet below defines a mutation which can be used to write data to the backend data store.
mutation UpvotePost($postId: Int!) {
  upvotePost(postId: $postId) {
    votes
  }
}
--
Android::
+
[source,java]
--
import org.aerogear.mobile.sync.SyncClient
import com.apollographql.apollo.api.Operation;

// Treat SyncClient as a Singleton and use the static "instance" of SyncClient
SyncClient client = SyncClient.getInstance();
UpvotePostMutation mutation = UpvotePostMutation.builder()
    .votes(3)
    .build();

SyncMuation sm = client.mutation(mutation);
Operation.data = sm.execute();
--
iOS::
+
[source,swift]
--
import Apollo
import AgsSync

// Treat Ags as a Singleton and use the static "instance" of AgsSync
AgsSync client = AgsSync.instance;
--
. Use the Apollo Client to use muations against the Apollo server
https://www.apollographql.com/docs/ios/mutations/
====

---

*Subscriptions*

The Apollo client wrapper classes can also be used to subscribe to and receive live streams from the specified url. 

[tabs]
====
GraphQL Schema::
+
[source,graphql]
--
// The graphql schema snippet below defines a subscription interface.

subscription onCommentAdded($repoFullName: String!){
  commentAdded(repoFullName: $repoFullName){
    id
    content
  }
}
--
Android::
+
[source,java]
--
import org.aerogear.mobile.sync.SyncClient
import com.apollographql.apollo.api.Operation;

// Treat SyncClient as a Singleton and use the static "instance" of SyncClient
SyncClient client = SyncClient.getInstance();
UpvotePostMutation mutation = UpvotePostMutation.builder()
    .votes(3)
    .build();

SyncMuation sm = client.mutation(mutation);
Operation.data = sm.execute();
--
iOS::
+
[source,swift]
--
import Apollo
import AgsSync

// Treat Ags as a Singleton and use the static "instance" of AgsSync
AgsSync client = AgsSync.instance;
--
. Use the Apollo Client to use muations against the Apollo server
https://www.apollographql.com/docs/ios/mutations/
====


https://www.apollographql.com/docs/android/essentials/mutations/
https://www.apollographql.com/docs/react/data/subscriptions/


Information about the apollo graphQL client for android can be found here: https://www.apollographql.com/docs/android/[appollo client for android].

link:./ds-SyncClient-class.html[Android SDK]

