= Overview

To make it easiser for developers to get started with our {sync-service} framework, we have built a sample application for developers to play with. With this app, developers can try out the many of the features offered by the {sync-service} framework, including:

* GraphQL Schema
* Offline Storage
* Conflict Resolution
* Subscriptions

In this section, we will go through the steps to setup the sample application on OpenShift.

= Prerequisites

- A running OpenShift cluster
- You have {org-name} {product-name} installed to the OpenShift cluster
- On your local machine, you need to have Node.js installed. It should be at least version 8.
- If you want to build the client as an iOS or Android app, you need to have the corresponding toolchain installed as well (Android SDK, or XCode).

= Deploy the Server

To deploy the server of the sample application, please follow the steps described in <<Provisioning {sync-service} Service>> with the following configurations:





= Setup and Run the Client App