= Getting Started

This section describes how to use the Voyager JavaScript client SDK to create mobile and web applications that can communicate with the Voyager server application. 

.Prerequisites

* The {sync-server} application is running either locally or on an OpenShift cluster

.Procedure

. Install required NPM packages
+
[source,bash]
----
$ npm install --save @aerogear/voyager-client
----

. Importing the package
+
[source,javascript]
----
import {
  createClient,
  strategies
} from '@aerogear/voyager-client';
----

. Configuration
+
To configure the Voyager client, a configuration object should be used. At a minimum, the `httpUrl` field is required and it is the url of the Voyager server application. If the client app uses subscription as well, then the `wsUrl` field is required too. For example:
+
[source,javascript]
----
let config = {
  httpUrl: "http://localhost:4000/graphql",
  wsUrl: "ws://localhost:4000/graphql",
}
----
+
// TODO: link to the API doc.
For other configuration options, please check out the API doc.

. Creating a Client
+
[source,javascript]
----
let client = createClient(config);
----

//TODO: explain a bit more about the high level structure of the client SDK, and the packages provided by the SDK and what they are for.