= Getting Started

This section describes how to use the Voyager JavaScript client SDK to create mobile and web applications that can communicate with the Voyager server application. 

.Prerequisites

* The Voyager server application is running either locally or on an OpenShift cluster

.Procedure

. Install required NPM packages
+
[source,bash]
----
$ npm install --save @aerogear/voyager-client
----

== Importing the package

[source,typescript]
----
import {
  createClient,
  strategies
} from '@aerogear/voyager-client';
----

== Configuration

An instance of `DataSyncConfig` can be used to configure the Voyager client. At a minimum, the `httpUrl` is required and it is the url of the Voyager server application. If the client app uses subscription as well, then the `wsUrl` field is required too. The example beblow demostrates how to create a new instance of `DataSyncConfig`:

[source,typescript]
----

let config: DataSyncConfig = {
  httpUrl: "http://localhost:4000/graphql",
  wsUrl: "ws://localhost:4000/graphql",
}
----

// TODO: link to the API doc.
For other configuration options, please check out the API docs for `DataSyncConfig`.

== Creating a Client

[source,typescript]
----
let client = createClient(config);
----

//TODO: explain a bit more about the high level structure of the client SDK, and the packages provided by the SDK and what they are for.