= Introduction

The {sync-service} Javascript client SDK is built on top of the popular link:https://www.apollographql.com/docs/react[Apollo GraphQL Javascript client], and it adds the following additional features: 

* Offline query and mutation support
* Conflict detection and resolution
* Audit logging

The client SDK can be used with all the major javascript frameworks that Apollo supports, please refer to their documentation for some of the basic concepts for each of the frameworks:

For React:
https://www.apollographql.com/docs/react/

For Angular:
https://www.apollographql.com/docs/angular/

== Cache

In order to support offline use cases, the client SDK strongly leverages Apollo Cache layer. Please refer link: https://www.apollographql.com/docs/react/advanced/caching.html[their documentation] for more information about caching in Apollo GraphQL.

=== Querying Data

To work with cache effectively, it is recommended that developers use the `cache-first` fetchPolicy when perform queries.

----
  return this.apollo.watchQuery<YourType>({
    query: YOUR_QUERY,
    fetchPolicy: 'cache-first',
  });
----

Cache will be fueled by subscriptions, pooling or regular queries happening in UI. Please see <<#client-offline-support, Offline Support>> section for more details.

== Required Field in GraphQL Types

A field called `id` is required in all the types when design the GraphQL schema for an application. The client SDK expects this field to be returned from the server for a query. Without this field some offline functionalities will not work properly.
