//':context:' is a vital parameter. See: http://asciidoctor.org/docs/user-manual/#include-multiple
[id='ref_terminology_{context}']

= {sync-service} Terminology

This section describes terminology that is associated with {sync-service}.

GraphQL:: A query language for your API, and a server-side runtime for executing queries by using a type system you define for your data. An alternative approach to REST for building APIs and applications. See link:https://graphql.org/learn[GraphQL].

Apollo:: Apollo is an implementation of GraphQL designed for the needs of product engineering teams building modern, data-driven applications. Apollo includes two open-source libraries, Apollo Server and Apollo Client. See link:https://www.apollographql.com[Apollo].

Apollo Server:: Apollo Server is a library for building GraphQL APIs in Node.js. A developer defines a GraphQL schema and a set of resolvers to implement each part of the schema. See link:https://www.apollographql.com/docs/apollo-server[Apollo Server].

Apollo Client:: Apollo Client is a JavaScript client library for building web and mobile applications powered by a GraphQL API. See link:https://www.apollographql.com/docs/react[Apollo Client].
