

//':context:' is a vital parameter. See: http://asciidoctor.org/docs/user-manual/#include-multiple
:context: schema_ui

[id='{context}_data_sources_ui']
= Defining a Schema using the {sync-service} UI

A schema describes the structure of the data the {sync-service} deals with. It allows you to configure
your data types, queries and mutations in a format that is independent of the underlying data source.
To learn more Schemas have a look at the link:https://graphql.org/learn/schema/[GraphQL documentation].

== The Schema Editor

The Schema Editor can be found under the `Schema` tab in the UI. It consists of a text editor where
you can write and edit your schema and a structure view on the right. To try it out you can use a simple schema like this:

```
type Query {
    notes: [Note]
}

type Comment {
    from: String
    text: String
}

type Note {
    text: String!
    comments: [Comment]
}
```

Save the schema by pressing the `Save Schema` button. Upon saving the {sync-service} will check your schema for errors and compile it to a JSON representation.
You can download this JSON representation by clicking on `Download Compiled Schema`. This is needed in the client SDKs.

NOTE: When defining https://graphql.org/learn/schema/#scalar-types[custom scalars] on your schema it is important to assert that the data types match the expected type. This is important as custom Scalar definitions could potentially lead to security vulnerabilities such as SQL Injection.

== Structure View

After saving a schema the structure view on the right side of the `Schema` tab will be updated. If your schema contains errors you will see the error message there.
Otherwise you will see a list of all your types, queries, mutations and subscriptions. This view is read only and can be used to quickly browse a schema.

== Playground

A playground is provided which allows you to test your changes to the schema. To use the playground, navigate to the tab in the UI and then write any queries or mutations you wish. Some useful features of the playground include code completion, query variables and full http header support. For more information about the playground and what is possible please visit link:https://github.com/prisma/graphql-playground[Prisma Playground].
