.Prerequisites

* [x] You have Node.js and npm installed.
* [x] You have created a node.js project

== Hello World {sync-service}

{sync-server} is a set of Node.js libraries that can be used to build a custom backend {sync-service} service using GraphQL.

{sync-server} is the starting point for developing a {sync-service} application. Used with link:https://expressjs.com/[Express], this module leverages Apollo Server and provides extension points for additional features and integrations.


In this example, you add libraries to your node.js project, create an `index.js` file, run the server, and confirm that it works.

. Add libraries to your Node.js application,
+
====
[source,bash]
----
$ npm install graphql <1>
$ npm install express <2>
$ npm install @aerogear/voyager-server <3>
----

<1> See https://graphql.org/
<2> See https://expressjs.com/
<3> The {sync-server} library that enables data sync
====

. Create an `index.js` file with the following content:
+
[source,javascript]
----
const express = require('express')
//Include our server libraries
const { VoyagerServer, gql } = require('@aerogear/voyager-server')

//Provide your graphql schema
const typeDefs = gql`
  type Query {
    hello: String
  }
`

//Create the resolvers for your schema
const resolvers = {
  Query: {
    hello: (obj, args, context, info) => {
      return `Hello world`
    }
  }
}

//Initialize the library with your Graphql information
const server = VoyagerServer({
  typeDefs,
  resolvers
})

//Connect the server to express
const app = express()
server.applyMiddleware({ app })

app.listen(4000, () =>
  console.log(`🚀 Server ready at http://localhost:4000/graphql`)
)
----

. Run the server:
+
[source,bash]
----
$ node index.js

🚀 Server ready at http://localhost:4000/graphql
----

. Browse `http://localhost:4000/graphql` and interact with the playground. For example:
+
[source,javascript]
----
{
  hello
}
----

. Check the output. For the example above, the output should be:
+
[source,javascript]
----
{
  "data": {
    "hello": "Hello world"
  }
}
----

To make it easier for developers to get started with our {sync-service} framework, see the link:https://github.com/aerogear/ionic-showcase[sample application]. In this app, you can explore a more complex schema.

Before proceeding, make sure you have an understanding of the following GraphQL concepts:

* Schema design
* Resolvers
* Subscriptions
