= Prerequisites
* [x] You have Node.js and npm installed.
* [x] You have created an empty node.js project with `npm init` and added the link:https://expressjs.com/[express] and graphql modules.

= Creating a Server App

{sync-server} is a set of Node.js libraries that can be used to build a custom backend {sync-service} service using GraphQL.

{sync-server} is the starting point for developing a {sync-service} application. Used with link:https://expressjs.com/[Express], this module leverages Apollo Server and provides extension points for additional features and integrations.

== Hello World Sync

Let's begin with writing our server with a "Hello World" example.  You will add the libraries to your node.js project, create the index.js file, run the server, and confirm that it works.

.Add our libraries to your Node.js application,
[source,bash]
----
npm install @aerogear/voyager-server
----

Below is a simple code example to get up and running with {sync-server}

.index.js
[source,javascript]
----
const express = require('express')
//Include our server libraries
const { VoyagerServer, gql } = require('@aerogear/voyager-server')

//Provide your graphql schema
const typeDefs = gql`
  type Query {
    hello: String
  }
`

//Create the resolvers for your schema
const resolvers = {
  Query: {
    hello: (obj, args, context, info) => {
      return `Hello world`
    }
  }
}

//Initialize the library with your Graphql information
const server = VoyagerServer({
  typeDefs,
  resolvers
})

//Connect the server to express
const app = express()
server.applyMiddleware({ app })

app.listen(4000, () =>
  console.log(`🚀 Server ready at http://localhost:4000/graphql`)
)
----

Now we should run our service and see that it works.

[source,bash]
----
node index.js
# Should output 🚀 Server ready at http://localhost:4000/graphql
----

The server should now be running.  You can browse to `http://localhost:4000/graphql` and interact with the playgroud.