// For more information, see: https://redhat-documentation.github.io/modular-docs/

[id='monitoring-with-sync-{context}']
= Monitoring the {sync-service} Service

After the {metrics-service} Service (includes Grafana for visualization and the Prometheus monitoring system) and {keycloak-service} Service are provisioned,
you should be able to see the "Data Sync Metrics" in the list of available dashboards.

.Prerequisites

* You have provisioned the xref:mobile-metrics.adoc[{metrics-service} service].
* You have provisioned the xref:data-sync.adoc[{sync-service}] service.
* The {metrics-service} Service and {keycloak-service} Service must be provisioned in the same OpenShift project to access data.

.Procedure

. Navigate to Grafana's exposed URL.
. Select Log in -> Home.
. Select *Data Sync Metrics*.

[discrete]
== Additional resources

* link:http://docs.grafana.org/features/panels/singlestat/#singlestat-panel[Singlestat Panel]
* link:http://docs.grafana.org/features/panels/graph/#graph-panel[Graph Panel]
* link:https://grafana.com/plugins/grafana-piechart-panel[Pie Chart]

== Dashboard panel descriptions

The Data Sync dashboard consists of several panels which give you an overview of the specific
events and resources, such as memory usage, CPU usage, resolved operation count etc.

Below you will find a detailed description of each panel and its values.

=== Singlestat Panels

Singlestat panels show you the main summary of a single data series.

* *CPU Usage*: CPU usage percentage of {sync-service} Service used currently.

* *Memory Usage*: The amount of memory currently used by the {sync-service} Service

=== Graph panels

Used to show how certain values change over time, e.g. the number of operations resolved.

* *Memory Usage in Time*: The amount of memory used by the {sync-service} Service over time

* *CPU Usage in Time*: The percentage of CPU used by the {sync-service} Service over time

* *Queries/Mutations Resolved*: Overview of the resolved queries and mutations over time

* *Resolver Timings*: Overview of the how long it took to resolve operations over time.
