// For more information, see: https://redhat-documentation.github.io/modular-docs/

[id='monitoring-keycloak-{context}']
= Viewing {metrics-service} Service Dashboards

The {metrics-service} Service gathers metrics data from mobile services and uses link:https://grafana.com/[Grafana^] to display that data.
A Grafana dashboard allows you to arrange panels and charts together to provide a visual overview of your metrics.
When you create an instance of a {product-name} service from the OpenShift service catalogue, a dashboard that shows metrics about that service is added to Grafana.
Also, when you configure your {mobile-client} to use metrics, you can see the metrics in Grafana.

.Prerequisites

* You have created an instance of a {product-name} service from the OpenShift service catalogue.
* If you edit the default mobile service dashboards, your changes will be lost whenever the associated mobile service is updated. Clone it before editing:
+
. Open the Dashboard you want to clone.
. Click the settings icon in the dashboard controls to show the *Settings* screen.
. Select the *Save As* option and enter in a name for the new dashboard, for example `Copy of Sync Service Dashboard`.

== Creating Dashboards in Grafana

.Procedure

. link:http://docs.grafana.org/[Create dashboards using *Drag and Drop* in Grafana^]

== Importing Dashboards

.Procedure

. link:http://docs.grafana.org/[Import and export Grafana dashboards using that JSON dsefinition^]

== Related Information

* See the Grafana http://docs.grafana.org/guides/getting_started/[Getting Started^] guide for an introduction to dashboards.

=== Modifying custom dashboards

You can create and modify custom dashboards to:
* visualize metrics from apps and back-end services that are not mobile services
* monitor additional metrics from mobile services that are not displayed by default
* monitor additional metrics from OpenShift that are not displayed by default
