

= Analyzing App Usage

This guide shows how to use app metrics to provide rich visualizations regarding app usage that can then drive development planning, for example, when should support for  version x.y of app end?'

[discrete]
== Viewing Dashboards

There are many visualisations available in the default dashboards in Grafana.
There are 2 dashboards where App Metrics data is shown:

* Mobile Service Dashboard (Summary data in the 'Mobile App Metrics' section)
* Mobile App Metrics Dashboard

In general, the summary data that is visible on the 'Mobile Services' Dashboard is also available on the 'Mobile App Metrics' dashboard, but in more detail.

[discrete]
== Analyzing App launches

An App launch is a metric event that occurs when an App is launched on a device.
The total number of App launches for a given time shows how many times an App was launched in that time, regardless of if it was the same device or different devices.
It can be useful as a gauge on how much activity the App has.
However, as it doesn't take into account multiple launches from the same device, it isn't useful as a gauge for 'stickiness' of the App.

[discrete]
== Analyzing unique clients

Every metric event has a unique client identifier associated with it.
This unique client identifier is generated the first time an App is started.
It is worth noting this identifier will be regenerated if a user re-installs an App.
The total number of unique clients for a given time shows how many users launched an App at least once.
This can be useful as a gauge on how many active App users there currently are.
The time range is an important factor when viewing the number of unique clients.
Viewing unique clients for the last year gives a very different insight than for the last week.
In Grafana, the time range can be changed in the top right of the Dashboard view.

[discrete]
== Analyzing unique clients per App

Every metric event has an App identifier associated with it.
An App identifier uniquely identifies an App.
It is bundled with the App binary.
There can be more than 1 App (each with a different App identifier) sending metrics events to the same Metrics Service.
For example, there might be an Admin Portal App and a Field Worker App both using the same back-end services and same {metrics-service} Service.
The number of unique clients per App gives a breakdown of all users by the App they are using.
However, if you only have 1 App there is no difference between the number of unique clients and the number of unique clients per App.

[discrete]
== Analyzing unique clients per platform

Every metric event has the platform associated with it.
An example of a platform is Android or iOS.
This can be useful for making decisions about which platform to put effort into.
However, if all your Apps are on a single platform, there is no difference between the number of unique clients and the number of unique clients per platform.

[discrete]
== Analyzing unique clients per sdk version

Every metric event has the AeroGear sdk version associated with it.
This can be useful for making decisions about what features to deprecate or drop support for, or applying backwards incompatible server changes/updates.
This metric will be more valuable as more versions of an App (with different sdk versions) are published.

[discrete]
== Analyzing unique clients per app version

Every metric event has the App version associated with it.
The App version is set by the developer.
Like the sdk version, this can be useful for making decisions about what features to deprecate or drop support for, or applying backwards incompatible server changes/updates.
It can also be useful to see the uptake rate of newly published versions of an App.

[discrete]
== Related Information

See Grafana documentation for more information on the following topics:

* link:http://docs.grafana.org/features/panels/singlestat/#singlestat-panel[Singlestat Panel^]
* link:http://docs.grafana.org/features/panels/graph/#graph-panel[Graph Panel^]
* link:https://grafana.com/plugins/grafana-piechart-panel[Pie Chart^]
